// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"github.com/kpenfound/greetings-api/.dagger/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Greetings) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source   *dagger.Directory
		Repo     string
		Image    string
		App      string
		Backend  *dagger.Backend
		Frontend *dagger.Frontend
	}
	concrete.Source = r.Source
	concrete.Repo = r.Repo
	concrete.Image = r.Image
	concrete.App = r.App
	concrete.Backend = r.Backend
	concrete.Frontend = r.Frontend
	return json.Marshal(&concrete)
}

func (r *Greetings) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source   *dagger.Directory
		Repo     string
		Image    string
		App      string
		Backend  *dagger.Backend
		Frontend *dagger.Frontend
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	r.Repo = concrete.Repo
	r.Image = concrete.Image
	r.App = concrete.App
	r.Backend = concrete.Backend
	r.Frontend = concrete.Frontend
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Greetings":
		switch fnName {
		case "Build":
			var parent Greetings
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Greetings).Build(&parent), nil
		case "DebugBrokenTestsPr":
			var parent Greetings
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var githubToken *dagger.Secret
			if inputArgs["githubToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["githubToken"]), &githubToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg githubToken", err))
				}
			}
			var commit string
			if inputArgs["commit"] != nil {
				err = json.Unmarshal([]byte(inputArgs["commit"]), &commit)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg commit", err))
				}
			}
			var model string
			if inputArgs["model"] != nil {
				err = json.Unmarshal([]byte(inputArgs["model"]), &model)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg model", err))
				}
			}
			return nil, (*Greetings).DebugBrokenTestsPr(&parent, ctx, githubToken, commit, model)
		case "DebugTests":
			var parent Greetings
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var model string
			if inputArgs["model"] != nil {
				err = json.Unmarshal([]byte(inputArgs["model"]), &model)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg model", err))
				}
			}
			return (*Greetings).DebugTests(&parent, ctx, model)
		case "Develop":
			var parent Greetings
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var assignment string
			if inputArgs["assignment"] != nil {
				err = json.Unmarshal([]byte(inputArgs["assignment"]), &assignment)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg assignment", err))
				}
			}
			var model string
			if inputArgs["model"] != nil {
				err = json.Unmarshal([]byte(inputArgs["model"]), &model)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg model", err))
				}
			}
			return (*Greetings).Develop(&parent, ctx, assignment, model), nil
		case "DevelopFeedback":
			var parent Greetings
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var assignment string
			if inputArgs["assignment"] != nil {
				err = json.Unmarshal([]byte(inputArgs["assignment"]), &assignment)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg assignment", err))
				}
			}
			var diff string
			if inputArgs["diff"] != nil {
				err = json.Unmarshal([]byte(inputArgs["diff"]), &diff)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg diff", err))
				}
			}
			var feedback string
			if inputArgs["feedback"] != nil {
				err = json.Unmarshal([]byte(inputArgs["feedback"]), &feedback)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg feedback", err))
				}
			}
			var model string
			if inputArgs["model"] != nil {
				err = json.Unmarshal([]byte(inputArgs["model"]), &model)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg model", err))
				}
			}
			return (*Greetings).DevelopFeedback(&parent, ctx, source, assignment, diff, feedback, model)
		case "DevelopPullRequest":
			var parent Greetings
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var githubToken *dagger.Secret
			if inputArgs["githubToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["githubToken"]), &githubToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg githubToken", err))
				}
			}
			var issueId int
			if inputArgs["issueId"] != nil {
				err = json.Unmarshal([]byte(inputArgs["issueId"]), &issueId)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg issueId", err))
				}
			}
			var model string
			if inputArgs["model"] != nil {
				err = json.Unmarshal([]byte(inputArgs["model"]), &model)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg model", err))
				}
			}
			return (*Greetings).DevelopPullRequest(&parent, ctx, githubToken, issueId, model)
		case "DevelopReview":
			var parent Greetings
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var assignment string
			if inputArgs["assignment"] != nil {
				err = json.Unmarshal([]byte(inputArgs["assignment"]), &assignment)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg assignment", err))
				}
			}
			var diff string
			if inputArgs["diff"] != nil {
				err = json.Unmarshal([]byte(inputArgs["diff"]), &diff)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg diff", err))
				}
			}
			var model string
			if inputArgs["model"] != nil {
				err = json.Unmarshal([]byte(inputArgs["model"]), &model)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg model", err))
				}
			}
			return (*Greetings).DevelopReview(&parent, ctx, source, assignment, diff, model)
		case "PullRequestFeedback":
			var parent Greetings
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var githubToken *dagger.Secret
			if inputArgs["githubToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["githubToken"]), &githubToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg githubToken", err))
				}
			}
			var issueId int
			if inputArgs["issueId"] != nil {
				err = json.Unmarshal([]byte(inputArgs["issueId"]), &issueId)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg issueId", err))
				}
			}
			var feedback string
			if inputArgs["feedback"] != nil {
				err = json.Unmarshal([]byte(inputArgs["feedback"]), &feedback)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg feedback", err))
				}
			}
			var model string
			if inputArgs["model"] != nil {
				err = json.Unmarshal([]byte(inputArgs["model"]), &model)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg model", err))
				}
			}
			return nil, (*Greetings).PullRequestFeedback(&parent, ctx, githubToken, issueId, feedback, model)
		case "PullRequestReview":
			var parent Greetings
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var githubToken *dagger.Secret
			if inputArgs["githubToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["githubToken"]), &githubToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg githubToken", err))
				}
			}
			var issueId int
			if inputArgs["issueId"] != nil {
				err = json.Unmarshal([]byte(inputArgs["issueId"]), &issueId)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg issueId", err))
				}
			}
			var model string
			if inputArgs["model"] != nil {
				err = json.Unmarshal([]byte(inputArgs["model"]), &model)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg model", err))
				}
			}
			return nil, (*Greetings).PullRequestReview(&parent, ctx, githubToken, issueId, model)
		case "Release":
			var parent Greetings
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var tag string
			if inputArgs["tag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tag"]), &tag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tag", err))
				}
			}
			var ghToken *dagger.Secret
			if inputArgs["ghToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ghToken"]), &ghToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ghToken", err))
				}
			}
			return (*Greetings).Release(&parent, ctx, tag, ghToken)
		case "":
			var parent Greetings
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var repo string
			if inputArgs["repo"] != nil {
				err = json.Unmarshal([]byte(inputArgs["repo"]), &repo)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg repo", err))
				}
			}
			var image string
			if inputArgs["image"] != nil {
				err = json.Unmarshal([]byte(inputArgs["image"]), &image)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg image", err))
				}
			}
			var app string
			if inputArgs["app"] != nil {
				err = json.Unmarshal([]byte(inputArgs["app"]), &app)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg app", err))
				}
			}
			return New(source, repo, image, app), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithObject(
				dag.TypeDef().WithObject("Greetings", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 10, 6)}).
					WithFunction(
						dag.Function("Build",
							dag.TypeDef().WithObject("Directory")).
							WithDescription("Build the backend and frontend for a specified environment").
							WithSourceMap(dag.SourceMap("main.go", 56, 1))).
					WithFunction(
						dag.Function("DebugBrokenTestsPr",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Debug broken tests on a pull request and comment fix suggestions").
							WithSourceMap(dag.SourceMap("debugger.go", 61, 1)).
							WithArg("githubToken", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{Description: "Github token with permissions to comment on the pull request", SourceMap: dag.SourceMap("debugger.go", 64, 2)}).
							WithArg("commit", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Git commit in Github", SourceMap: dag.SourceMap("debugger.go", 66, 2)}).
							WithArg("model", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "The model to use to debug debug tests\n+default = \"claude-sonnet-4-0\"", SourceMap: dag.SourceMap("debugger.go", 70, 2)})).
					WithFunction(
						dag.Function("DebugTests",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Debug broken tests. Returns a unified diff of the test fixes").
							WithSourceMap(dag.SourceMap("debugger.go", 12, 1)).
							WithArg("model", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "The model to use to debug debug tests\n+default = \"claude-sonnet-4-0\"", SourceMap: dag.SourceMap("debugger.go", 17, 2)})).
					WithFunction(
						dag.Function("Develop",
							dag.TypeDef().WithObject("Directory")).
							WithDescription("Complete an assignment for the greetings project and get back the completed work").
							WithSourceMap(dag.SourceMap("develop.go", 12, 1)).
							WithArg("assignment", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "The assignment to complete", SourceMap: dag.SourceMap("develop.go", 15, 2)}).
							WithArg("model", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "The model to use to complete the assignment\n+default = \"claude-sonnet-4-0\"", SourceMap: dag.SourceMap("develop.go", 19, 2)})).
					WithFunction(
						dag.Function("DevelopFeedback",
							dag.TypeDef().WithObject("Directory")).
							WithDescription("Agent to develop changes based on feedback on changes made in a Directory").
							WithSourceMap(dag.SourceMap("develop.go", 98, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{Description: "Source directory containing the developed changes", SourceMap: dag.SourceMap("develop.go", 101, 2)}).
							WithArg("assignment", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Original assignment being developed", SourceMap: dag.SourceMap("develop.go", 103, 2)}).
							WithArg("diff", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Diff of the changes done so far", SourceMap: dag.SourceMap("develop.go", 105, 2)}).
							WithArg("feedback", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Feedback given to the changes done so far", SourceMap: dag.SourceMap("develop.go", 107, 2)}).
							WithArg("model", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "The model to use to complete the assignment\n+default = \"claude-sonnet-4-0\"", SourceMap: dag.SourceMap("develop.go", 111, 2)})).
					WithFunction(
						dag.Function("DevelopPullRequest",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Develop changes based on a Github issue and open a pull request").
							WithSourceMap(dag.SourceMap("develop.go", 49, 1)).
							WithArg("githubToken", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{Description: "Github token with permissions to create a pull request", SourceMap: dag.SourceMap("develop.go", 52, 2)}).
							WithArg("issueId", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{Description: "The github issue to complete", SourceMap: dag.SourceMap("develop.go", 54, 2)}).
							WithArg("model", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "The model to use to complete the assignment\n+default = \"claude-sonnet-4-0\"", SourceMap: dag.SourceMap("develop.go", 58, 2)})).
					WithFunction(
						dag.Function("DevelopReview",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Agent to review changes made in a Directory").
							WithSourceMap(dag.SourceMap("review.go", 11, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{Description: "Source directory containing the developed changes", SourceMap: dag.SourceMap("review.go", 14, 2)}).
							WithArg("assignment", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Original assignment being developed", SourceMap: dag.SourceMap("review.go", 16, 2)}).
							WithArg("diff", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Git diff of the changes so far", SourceMap: dag.SourceMap("review.go", 18, 2)}).
							WithArg("model", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "The model to use to complete the assignment\n+default = \"claude-sonnet-4-0\"", SourceMap: dag.SourceMap("review.go", 22, 2)})).
					WithFunction(
						dag.Function("PullRequestFeedback",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Receive feedback on an open pull request via slash command").
							WithSourceMap(dag.SourceMap("develop.go", 140, 1)).
							WithArg("githubToken", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{Description: "Github token with permissions to create a pull request", SourceMap: dag.SourceMap("develop.go", 143, 2)}).
							WithArg("issueId", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{Description: "The github issue to complete", SourceMap: dag.SourceMap("develop.go", 145, 2)}).
							WithArg("feedback", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "The feedback recieved on the pull request", SourceMap: dag.SourceMap("develop.go", 147, 2)}).
							WithArg("model", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "The model to use to complete the assignment\n+default = \"claude-sonnet-4-0\"", SourceMap: dag.SourceMap("develop.go", 151, 2)})).
					WithFunction(
						dag.Function("PullRequestReview",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Review an open pull request via slash command").
							WithSourceMap(dag.SourceMap("review.go", 47, 1)).
							WithArg("githubToken", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{Description: "Github token with permissions to create a pull request", SourceMap: dag.SourceMap("review.go", 50, 2)}).
							WithArg("issueId", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{Description: "The github issue to complete", SourceMap: dag.SourceMap("review.go", 52, 2)}).
							WithArg("model", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "The model to use to complete the assignment\n+default = \"claude-sonnet-4-0\"", SourceMap: dag.SourceMap("review.go", 56, 2)})).
					WithFunction(
						dag.Function("Release",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Create a GitHub release").
							WithSourceMap(dag.SourceMap("main.go", 63, 1)).
							WithArg("tag", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 63, 50)}).
							WithArg("ghToken", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 63, 62)})).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("Greetings")).
							WithSourceMap(dag.SourceMap("main.go", 25, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 29, 2), DefaultPath: "/", Ignore: []string{".git", "**/node_modules"}}).
							WithArg("repo", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 32, 2), DefaultValue: dagger.JSON("\"github.com/kpenfound/greetings-api\"")}).
							WithArg("image", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 35, 2), DefaultValue: dagger.JSON("\"kylepenfound/greetings-api:latest\"")}).
							WithArg("app", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 38, 2), DefaultValue: dagger.JSON("\"dagger-demo\"")}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
