// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/code-workspace/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r CodeWorkspace) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Work    *dagger.Directory
		Start   *dagger.Directory
		Checker any
	}
	concrete.Work = r.Work
	concrete.Start = r.Start
	concrete.Checker = r.Checker
	return json.Marshal(&concrete)
}

func (r *CodeWorkspace) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Work    *dagger.Directory
		Start   *dagger.Directory
		Checker *checkableImpl
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Work = concrete.Work
	r.Start = concrete.Start
	r.Checker = concrete.Checker.toIface()
	return nil
}

type CheckableID = dagger.ID

func LoadCheckableFromID(r *dagger.Client, id CheckableID) Checkable {
	return &checkableImpl{query: r.QueryBuilder().Select("node").Arg("id", id).InlineFragment("CodeWorkspaceCheckable")}
}

type checkableImpl struct {
	query          *querybuilder.Selection
	id             *CheckableID
	checkDirectory *string
}

func (r *checkableImpl) WithGraphQLQuery(q *querybuilder.Selection) Checkable {
	return &checkableImpl{query: q}
}

func (r *checkableImpl) XXX_GraphQLType() string {
	return "CodeWorkspaceCheckable"
}

func (r *checkableImpl) XXX_GraphQLIDType() string {
	return "ID"
}

func (r *checkableImpl) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *checkableImpl) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("\"\""), nil
	}
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

func (r *checkableImpl) UnmarshalJSON(bs []byte) error {
	var id CheckableID
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = checkableImpl{query: dag.QueryBuilder().Select("node").Arg("id", id).InlineFragment("CodeWorkspaceCheckable")}
	return nil
}

func (r *checkableImpl) toIface() Checkable {
	if r == nil {
		return nil
	}
	return r
}

func (r *checkableImpl) ID(ctx context.Context) (CheckableID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")
	var response CheckableID
	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *checkableImpl) CheckDirectory(ctx context.Context, source *dagger.Directory) (string, error) {
	if r.checkDirectory != nil {
		return *r.checkDirectory, nil
	}
	q := r.query.Select("checkDirectory")
	q = q.Arg("source", source)

	var response string
	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *checkableImpl) FormatFile(source *dagger.Directory, path string) *dagger.Directory {
	q := r.query.Select("formatFile")
	q = q.Arg("source", source)

	q = q.Arg("path", path)

	return (&dagger.Directory{}).WithGraphQLQuery(q)
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "CodeWorkspace":
		switch fnName {
		case "Check":
			var parent CodeWorkspace
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*CodeWorkspace).Check(&parent, ctx)
		case "Diff":
			var parent CodeWorkspace
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*CodeWorkspace).Diff(&parent, ctx)
		case "Read":
			var parent CodeWorkspace
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var path string
			if inputArgs["path"] != nil {
				err = json.Unmarshal([]byte(inputArgs["path"]), &path)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg path", err))
				}
			}
			return (*CodeWorkspace).Read(&parent, ctx, path)
		case "Reset":
			var parent CodeWorkspace
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*CodeWorkspace).Reset(&parent), nil
		case "Tree":
			var parent CodeWorkspace
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*CodeWorkspace).Tree(&parent, ctx)
		case "Write":
			var parent CodeWorkspace
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var path string
			if inputArgs["path"] != nil {
				err = json.Unmarshal([]byte(inputArgs["path"]), &path)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg path", err))
				}
			}
			var contents string
			if inputArgs["contents"] != nil {
				err = json.Unmarshal([]byte(inputArgs["contents"]), &contents)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg contents", err))
				}
			}
			return (*CodeWorkspace).Write(&parent, ctx, path, contents), nil
		case "":
			var parent CodeWorkspace
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var checker *checkableImpl
			if inputArgs["checker"] != nil {
				err = json.Unmarshal([]byte(inputArgs["checker"]), &checker)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg checker", err))
				}
			}
			return New(source, checker.toIface()), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithDescription("A generated module for CodeWorkspace functions\n").
			WithObject(
				dag.TypeDef().WithObject("CodeWorkspace", dagger.TypeDefWithObjectOpts{Description: "Place to do work and check it", SourceMap: dag.SourceMap("main.go", 18, 6)}).
					WithFunction(
						dag.Function("Check",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Run the tests in the workspace").
							WithSourceMap(dag.SourceMap("main.go", 78, 1))).
					WithFunction(
						dag.Function("Diff",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Show the changes made to the workspace so far in unified diff format").
							WithSourceMap(dag.SourceMap("main.go", 83, 1))).
					WithFunction(
						dag.Function("Read",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Read the contents of a file in the workspace at the given path").
							WithSourceMap(dag.SourceMap("main.go", 40, 1)).
							WithArg("path", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Path to read the file at", SourceMap: dag.SourceMap("main.go", 43, 2)})).
					WithFunction(
						dag.Function("Reset",
							dag.TypeDef().WithObject("CodeWorkspace")).
							WithDescription("Reset the workspace to the original state").
							WithSourceMap(dag.SourceMap("main.go", 64, 1))).
					WithFunction(
						dag.Function("Tree",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("List the files in the workspace in tree format").
							WithSourceMap(dag.SourceMap("main.go", 70, 1))).
					WithFunction(
						dag.Function("Write",
							dag.TypeDef().WithObject("CodeWorkspace")).
							WithDescription("Write the contents of a file in the workspace at the given path").
							WithSourceMap(dag.SourceMap("main.go", 49, 1)).
							WithArg("path", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Path to write the file to", SourceMap: dag.SourceMap("main.go", 52, 2)}).
							WithArg("contents", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Contents to write to the file", SourceMap: dag.SourceMap("main.go", 54, 2)})).
					WithField("Work", dag.TypeDef().WithObject("Directory"), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("main.go", 19, 2)}).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("CodeWorkspace")).
							WithSourceMap(dag.SourceMap("main.go", 26, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{Description: "Initial state of the workspace", SourceMap: dag.SourceMap("main.go", 28, 2)}).
							WithArg("checker", dag.TypeDef().WithInterface("Checkable"), dagger.FunctionWithArgOpts{Description: "Checker to use for testing", SourceMap: dag.SourceMap("main.go", 30, 2)}))).
			WithInterface(
				dag.TypeDef().WithInterface("Checkable", dagger.TypeDefWithInterfaceOpts{Description: "Interface for something that can be checked", SourceMap: dag.SourceMap("main.go", 11, 6)}).
					WithFunction(
						dag.Function("CheckDirectory",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithSourceMap(dag.SourceMap("main.go", 13, 16)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 13, 38)})).
					WithFunction(
						dag.Function("FormatFile",
							dag.TypeDef().WithObject("Directory")).
							WithSourceMap(dag.SourceMap("main.go", 14, 12)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 14, 13)}).
							WithArg("path", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 14, 39)}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
