// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Backend struct { // backend (../../../.dagger/backend/main.go:11:6)
	query *querybuilder.Selection

	check          *string
	checkDirectory *string
	id             *BackendID
	lint           *string
	unitTest       *string
}

func (r *Backend) WithGraphQLQuery(q *querybuilder.Selection) *Backend {
	return &Backend{
		query: q,
	}
}

// BackendBinaryOpts contains options for Backend.Binary
type BackendBinaryOpts struct {
	Arch string // backend (../../../.dagger/backend/main.go:76:2)
}

// Return the compiled backend binary for a particular architecture
func (r *Backend) Binary(opts ...BackendBinaryOpts) *File { // backend (../../../.dagger/backend/main.go:74:1)
	q := r.query.Select("binary")
	for i := len(opts) - 1; i >= 0; i-- {
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
	}

	return &File{
		query: q,
	}
}

// BackendBuildOpts contains options for Backend.Build
type BackendBuildOpts struct {
	Arch string // backend (../../../.dagger/backend/main.go:62:2)
}

// Build the backend
func (r *Backend) Build(opts ...BackendBuildOpts) *Directory { // backend (../../../.dagger/backend/main.go:60:1)
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
	}

	return &Directory{
		query: q,
	}
}

// Checker
func (r *Backend) Check(ctx context.Context) (string, error) { // backend (../../../.dagger/backend/main.go:47:1)
	if r.check != nil {
		return *r.check, nil
	}
	q := r.query.Select("check")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Stateless checker
func (r *Backend) CheckDirectory(ctx context.Context, source *Directory) (string, error) { // backend (../../../.dagger/backend/main.go:105:1)
	assertNotNil("source", source)
	if r.checkDirectory != nil {
		return *r.checkDirectory, nil
	}
	q := r.query.Select("checkDirectory")
	q = q.Arg("source", source)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// BackendContainerOpts contains options for Backend.Container
type BackendContainerOpts struct {
	Arch string // backend (../../../.dagger/backend/main.go:85:2)
}

// Get a container ready to run the backend
func (r *Backend) Container(opts ...BackendContainerOpts) *Container { // backend (../../../.dagger/backend/main.go:83:1)
	q := r.query.Select("container")
	for i := len(opts) - 1; i >= 0; i-- {
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
	}

	return &Container{
		query: q,
	}
}

// Formatter
func (r *Backend) Format() *Directory { // backend (../../../.dagger/backend/main.go:38:1)
	q := r.query.Select("format")

	return &Directory{
		query: q,
	}
}

// Stateless formatter
func (r *Backend) FormatDirectory(source *Directory) *Directory { // backend (../../../.dagger/backend/main.go:114:1)
	assertNotNil("source", source)
	q := r.query.Select("formatDirectory")
	q = q.Arg("source", source)

	return &Directory{
		query: q,
	}
}

// Stateless formatter
func (r *Backend) FormatFile(source *Directory, path string) *Directory { // backend (../../../.dagger/backend/main.go:123:1)
	assertNotNil("source", source)
	q := r.query.Select("formatFile")
	q = q.Arg("source", source)
	q = q.Arg("path", path)

	return &Directory{
		query: q,
	}
}

// A unique identifier for this Backend.
func (r *Backend) ID(ctx context.Context) (BackendID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response BackendID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Backend) XXX_GraphQLType() string {
	return "Backend"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Backend) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Backend) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Backend) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Backend) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Backend{query: selectNode(dag.query, id, "Backend")}
	return nil
}

// Lint the backend Go code
func (r *Backend) Lint(ctx context.Context) (string, error) { // backend (../../../.dagger/backend/main.go:30:1)
	if r.lint != nil {
		return *r.lint, nil
	}
	q := r.query.Select("lint")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Get a Service to run the backend
func (r *Backend) Serve() *Service { // backend (../../../.dagger/backend/main.go:100:1)
	q := r.query.Select("serve")

	return &Service{
		query: q,
	}
}

func (r *Backend) Source() *Directory { // backend (../../../.dagger/backend/main.go:12:2)
	q := r.query.Select("source")

	return &Directory{
		query: q,
	}
}

// Run the unit tests for the backend
func (r *Backend) UnitTest(ctx context.Context) (string, error) { // backend (../../../.dagger/backend/main.go:22:1)
	if r.unitTest != nil {
		return *r.unitTest, nil
	}
	q := r.query.Select("unitTest")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsCodeWorkspaceCheckable returns this Backend as a CodeWorkspaceCheckable.
// This is a local type conversion — no GraphQL call.
func (r *Backend) AsCodeWorkspaceCheckable() *CodeWorkspaceCheckable {
	return &CodeWorkspaceCheckable{
		query: r.query,
	}
}

// AsNode returns this Backend as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Backend) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Retrieve the binding value, as type Backend
func (r *Binding) AsBackend() *Backend { // backend (../../../.dagger/backend/main.go:11:6)
	q := r.query.Select("asBackend")

	return &Backend{
		query: q,
	}
}

// Create or update a binding of type Backend in the environment
func (r *Env) WithBackendInput(name string, value *Backend, description string) *Env { // backend (../../../.dagger/backend/main.go:11:6)
	assertNotNil("value", value)
	q := r.query.Select("withBackendInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Backend output to be assigned in the environment
func (r *Env) WithBackendOutput(name string, description string) *Env { // backend (../../../.dagger/backend/main.go:11:6)
	q := r.query.Select("withBackendOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

func (r *Query) Backend(source *Directory) *Backend { // backend (../../../.dagger/backend/main.go:15:1)
	assertNotNil("source", source)
	q := r.query.Select("backend")
	q = q.Arg("source", source)

	return &Backend{
		query: q,
	}
}
