// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Frontend
func (r *Binding) AsFrontend() *Frontend { // frontend (../../../.dagger/frontend/src/index.ts:15:14)
	q := r.query.Select("asFrontend")

	return &Frontend{
		query: q,
	}
}

// Create or update a binding of type Frontend in the environment
func (r *Env) WithFrontendInput(name string, value *Frontend, description string) *Env { // frontend (../../../.dagger/frontend/src/index.ts:15:14)
	assertNotNil("value", value)
	q := r.query.Select("withFrontendInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Frontend output to be assigned in the environment
func (r *Env) WithFrontendOutput(name string, description string) *Env { // frontend (../../../.dagger/frontend/src/index.ts:15:14)
	q := r.query.Select("withFrontendOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Frontend struct { // frontend (../../../.dagger/frontend/src/index.ts:15:14)
	query *querybuilder.Selection

	checkDirectory *string
	id             *FrontendID
}

func (r *Frontend) WithGraphQLQuery(q *querybuilder.Selection) *Frontend {
	return &Frontend{
		query: q,
	}
}

func (r *Frontend) Build() *Directory { // frontend (../../../.dagger/frontend/src/index.ts:37:3)
	q := r.query.Select("build")

	return &Directory{
		query: q,
	}
}

func (r *Frontend) CheckDirectory(ctx context.Context, source *Directory) (string, error) { // frontend (../../../.dagger/frontend/src/index.ts:59:9)
	assertNotNil("source", source)
	if r.checkDirectory != nil {
		return *r.checkDirectory, nil
	}
	q := r.query.Select("checkDirectory")
	q = q.Arg("source", source)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *Frontend) Format() *Directory { // frontend (../../../.dagger/frontend/src/index.ts:24:3)
	q := r.query.Select("format")

	return &Directory{
		query: q,
	}
}

func (r *Frontend) FormatDirectory(source *Directory) *Directory { // frontend (../../../.dagger/frontend/src/index.ts:73:3)
	assertNotNil("source", source)
	q := r.query.Select("formatDirectory")
	q = q.Arg("source", source)

	return &Directory{
		query: q,
	}
}

func (r *Frontend) FormatFile(source *Directory, path string) *Directory { // frontend (../../../.dagger/frontend/src/index.ts:79:3)
	assertNotNil("source", source)
	q := r.query.Select("formatFile")
	q = q.Arg("source", source)
	q = q.Arg("path", path)

	return &Directory{
		query: q,
	}
}

// A unique identifier for this Frontend.
func (r *Frontend) ID(ctx context.Context) (FrontendID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response FrontendID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Frontend) XXX_GraphQLType() string {
	return "Frontend"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Frontend) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Frontend) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Frontend) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Frontend) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Frontend{query: selectNode(dag.query, id, "Frontend")}
	return nil
}

func (r *Frontend) Serve() *Service { // frontend (../../../.dagger/frontend/src/index.ts:43:3)
	q := r.query.Select("serve")

	return &Service{
		query: q,
	}
}

func (r *Frontend) Source() *Directory { // frontend (../../../.dagger/frontend/src/index.ts:17:3)
	q := r.query.Select("source")

	return &Directory{
		query: q,
	}
}

// AsCodeWorkspaceCheckable returns this Frontend as a CodeWorkspaceCheckable.
// This is a local type conversion — no GraphQL call.
func (r *Frontend) AsCodeWorkspaceCheckable() *CodeWorkspaceCheckable {
	return &CodeWorkspaceCheckable{
		query: r.query,
	}
}

// AsNode returns this Frontend as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Frontend) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// FrontendOpts contains options for Query.Frontend
type FrontendOpts struct {
	Source *Directory // frontend (../../../.dagger/frontend/src/index.ts:19:54)
}

// A generated module for Frontend functions
func (r *Query) Frontend(opts ...FrontendOpts) *Frontend { // frontend (../../../:0:0)
	q := r.query.Select("frontend")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	return &Frontend{
		query: q,
	}
}
