// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type GithubIssue
func (r *Binding) AsGithubIssue() *GithubIssue { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L19)
	q := r.query.Select("asGithubIssue")

	return &GithubIssue{
		query: q,
	}
}

// Retrieve the binding value, as type GithubIssueComment
func (r *Binding) AsGithubIssueComment() *GithubIssueComment { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L143)
	q := r.query.Select("asGithubIssueComment")

	return &GithubIssueComment{
		query: q,
	}
}

// Retrieve the binding value, as type GithubIssueData
func (r *Binding) AsGithubIssueData() *GithubIssueData { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L34)
	q := r.query.Select("asGithubIssueData")

	return &GithubIssueData{
		query: q,
	}
}

// Retrieve the binding value, as type GithubIssueTemplate
func (r *Binding) AsGithubIssueTemplate() *GithubIssueTemplate { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L526)
	q := r.query.Select("asGithubIssueTemplate")

	return &GithubIssueTemplate{
		query: q,
	}
}

// Create or update a binding of type GithubIssueComment in the environment
func (r *Env) WithGithubIssueCommentInput(name string, value *GithubIssueComment, description string) *Env { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L143)
	assertNotNil("value", value)
	q := r.query.Select("withGithubIssueCommentInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired GithubIssueComment output to be assigned in the environment
func (r *Env) WithGithubIssueCommentOutput(name string, description string) *Env { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L143)
	q := r.query.Select("withGithubIssueCommentOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type GithubIssueData in the environment
func (r *Env) WithGithubIssueDataInput(name string, value *GithubIssueData, description string) *Env { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L34)
	assertNotNil("value", value)
	q := r.query.Select("withGithubIssueDataInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired GithubIssueData output to be assigned in the environment
func (r *Env) WithGithubIssueDataOutput(name string, description string) *Env { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L34)
	q := r.query.Select("withGithubIssueDataOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type GithubIssue in the environment
func (r *Env) WithGithubIssueInput(name string, value *GithubIssue, description string) *Env { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L19)
	assertNotNil("value", value)
	q := r.query.Select("withGithubIssueInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired GithubIssue output to be assigned in the environment
func (r *Env) WithGithubIssueOutput(name string, description string) *Env { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L19)
	q := r.query.Select("withGithubIssueOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type GithubIssueTemplate in the environment
func (r *Env) WithGithubIssueTemplateInput(name string, value *GithubIssueTemplate, description string) *Env { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L526)
	assertNotNil("value", value)
	q := r.query.Select("withGithubIssueTemplateInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired GithubIssueTemplate output to be assigned in the environment
func (r *Env) WithGithubIssueTemplateOutput(name string, description string) *Env { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L526)
	q := r.query.Select("withGithubIssueTemplateOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type GithubIssue struct { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L19)
	query *querybuilder.Selection

	createPullRequestCommit     *Void
	getPrForCommit              *int
	id                          *GithubIssueID
	listCommentsUnified         *string
	listUnified                 *string
	templatesUnified            *string
	writeComment                *Void
	writePullRequestCodeComment *Void
}

func (r *GithubIssue) WithGraphQLQuery(q *querybuilder.Selection) *GithubIssue {
	return &GithubIssue{
		query: q,
	}
}

// GithubIssueCreatePullRequestOpts contains options for GithubIssue.CreatePullRequest
type GithubIssueCreatePullRequestOpts struct {
	//
	// branch name for pull request
	//
	Branch string // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L387)
	//
	// base branch for pull request
	//
	//
	// Default: "main"
	Base string // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L390)
}

// Create a Github Pull Request
func (r *GithubIssue) CreatePullRequest(repo string, title string, body string, source *Directory, opts ...GithubIssueCreatePullRequestOpts) *GithubIssueData { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L375)
	assertNotNil("source", source)
	q := r.query.Select("createPullRequest")
	for i := len(opts) - 1; i >= 0; i-- {
		// `branch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Branch) {
			q = q.Arg("branch", opts[i].Branch)
		}
		// `base` optional argument
		if !querybuilder.IsZeroValue(opts[i].Base) {
			q = q.Arg("base", opts[i].Base)
		}
	}
	q = q.Arg("repo", repo)
	q = q.Arg("title", title)
	q = q.Arg("body", body)
	q = q.Arg("source", source)

	return &GithubIssueData{
		query: q,
	}
}

// Create a commit on a Github Pull Request
func (r *GithubIssue) CreatePullRequestCommit(ctx context.Context, repo string, source *Directory, branch string) error { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L326)
	assertNotNil("source", source)
	if r.createPullRequestCommit != nil {
		return nil
	}
	q := r.query.Select("createPullRequestCommit")
	q = q.Arg("repo", repo)
	q = q.Arg("source", source)
	q = q.Arg("branch", branch)

	return q.Execute(ctx)
}

// Gets the pull request number for a commit
func (r *GithubIssue) GetPrForCommit(ctx context.Context, repo string, commit string) (int, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L289)
	if r.getPrForCommit != nil {
		return *r.getPrForCommit, nil
	}
	q := r.query.Select("getPrForCommit")
	q = q.Arg("repo", repo)
	q = q.Arg("commit", commit)

	var response int

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this GithubIssue.
func (r *GithubIssue) ID(ctx context.Context) (GithubIssueID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response GithubIssueID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *GithubIssue) XXX_GraphQLType() string {
	return "GithubIssue"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *GithubIssue) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *GithubIssue) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *GithubIssue) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *GithubIssue) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = GithubIssue{query: selectNode(dag.query, id, "GithubIssue")}
	return nil
}

// GithubIssueListOpts contains options for GithubIssue.List
type GithubIssueListOpts struct {
	//
	// Page of issues to read. There are 10 per page
	//
	//
	// Default: 1
	Page int // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L59)
}

// List Github issues for a repository
func (r *GithubIssue) List(ctx context.Context, repo string, opts ...GithubIssueListOpts) ([]GithubIssueData, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L53)
	q := r.query.Select("list")
	for i := len(opts) - 1; i >= 0; i-- {
		// `page` optional argument
		if !querybuilder.IsZeroValue(opts[i].Page) {
			q = q.Arg("page", opts[i].Page)
		}
	}
	q = q.Arg("repo", repo)

	q = q.Select("id")

	type list struct {
		Id GithubIssueDataID
	}

	convert := func(fields []list) []GithubIssueData {
		out := []GithubIssueData{}

		for i := range fields {
			val := GithubIssueData{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "GithubIssueData")
			out = append(out, val)
		}

		return out
	}
	var response []list

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// List all of the comments on a Github issue or pull request
func (r *GithubIssue) ListComments(ctx context.Context, repo string, issueId int) ([]GithubIssueComment, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L150)
	q := r.query.Select("listComments")
	q = q.Arg("repo", repo)
	q = q.Arg("issueId", issueId)

	q = q.Select("id")

	type listComments struct {
		Id GithubIssueCommentID
	}

	convert := func(fields []listComments) []GithubIssueComment {
		out := []GithubIssueComment{}

		for i := range fields {
			val := GithubIssueComment{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "GithubIssueComment")
			out = append(out, val)
		}

		return out
	}
	var response []listComments

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// List all of the comments on a Github issue or pull request and return a readable output for llms
func (r *GithubIssue) ListCommentsUnified(ctx context.Context, repo string, issueId int) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L186)
	if r.listCommentsUnified != nil {
		return *r.listCommentsUnified, nil
	}
	q := r.query.Select("listCommentsUnified")
	q = q.Arg("repo", repo)
	q = q.Arg("issueId", issueId)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GithubIssueListUnifiedOpts contains options for GithubIssue.ListUnified
type GithubIssueListUnifiedOpts struct {
	//
	// Page of issues to read. There are 10 per page
	//
	//
	// Default: 1
	Page int // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L103)
}

// List Github issues for a repository and return a readable output for llms
func (r *GithubIssue) ListUnified(ctx context.Context, repo string, opts ...GithubIssueListUnifiedOpts) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L97)
	if r.listUnified != nil {
		return *r.listUnified, nil
	}
	q := r.query.Select("listUnified")
	for i := len(opts) - 1; i >= 0; i-- {
		// `page` optional argument
		if !querybuilder.IsZeroValue(opts[i].Page) {
			q = q.Arg("page", opts[i].Page)
		}
	}
	q = q.Arg("repo", repo)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Read a Github issue from a repository
func (r *GithubIssue) Read(repo string, issueId int) *GithubIssueData { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L119)
	q := r.query.Select("read")
	q = q.Arg("repo", repo)
	q = q.Arg("issueId", issueId)

	return &GithubIssueData{
		query: q,
	}
}

// Retruns the github issue templates
func (r *GithubIssue) Templates(ctx context.Context, repo string) ([]GithubIssueTemplate, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L532)
	q := r.query.Select("templates")
	q = q.Arg("repo", repo)

	q = q.Select("id")

	type templates struct {
		Id GithubIssueTemplateID
	}

	convert := func(fields []templates) []GithubIssueTemplate {
		out := []GithubIssueTemplate{}

		for i := range fields {
			val := GithubIssueTemplate{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "GithubIssueTemplate")
			out = append(out, val)
		}

		return out
	}
	var response []templates

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// Retruns the github issue templates in a readable output
func (r *GithubIssue) TemplatesUnified(ctx context.Context, repo string) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L572)
	if r.templatesUnified != nil {
		return *r.templatesUnified, nil
	}
	q := r.query.Select("templatesUnified")
	q = q.Arg("repo", repo)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Create a github issue in a repository TODO: NOT YET IMPLEMENTED
func (r *GithubIssue) Write(repo string, title string, body string) *GithubIssueData { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L130)
	q := r.query.Select("write")
	q = q.Arg("repo", repo)
	q = q.Arg("title", title)
	q = q.Arg("body", body)

	return &GithubIssueData{
		query: q,
	}
}

// Write a comment on a Github issue
func (r *GithubIssue) WriteComment(ctx context.Context, repo string, issueId int, body string) error { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L210)
	if r.writeComment != nil {
		return nil
	}
	q := r.query.Select("writeComment")
	q = q.Arg("repo", repo)
	q = q.Arg("issueId", issueId)
	q = q.Arg("body", body)

	return q.Execute(ctx)
}

// Write a code suggestion on a Github pull request
func (r *GithubIssue) WritePullRequestCodeComment(ctx context.Context, repo string, issueId int, commit string, body string, path string, side string, line int) error { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L240)
	if r.writePullRequestCodeComment != nil {
		return nil
	}
	q := r.query.Select("writePullRequestCodeComment")
	q = q.Arg("repo", repo)
	q = q.Arg("issueId", issueId)
	q = q.Arg("commit", commit)
	q = q.Arg("body", body)
	q = q.Arg("path", path)
	q = q.Arg("side", side)
	q = q.Arg("line", line)

	return q.Execute(ctx)
}

// AsNode returns this GithubIssue as a Node.
// This is a local type conversion — no GraphQL call.
func (r *GithubIssue) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// A Github issue comment
type GithubIssueComment struct { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L143)
	query *querybuilder.Selection

	author    *string
	body      *string
	createdAt *string
	id        *GithubIssueCommentID
}

func (r *GithubIssueComment) WithGraphQLQuery(q *querybuilder.Selection) *GithubIssueComment {
	return &GithubIssueComment{
		query: q,
	}
}

func (r *GithubIssueComment) Author(ctx context.Context) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L144)
	if r.author != nil {
		return *r.author, nil
	}
	q := r.query.Select("author")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *GithubIssueComment) Body(ctx context.Context) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L145)
	if r.body != nil {
		return *r.body, nil
	}
	q := r.query.Select("body")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *GithubIssueComment) CreatedAt(ctx context.Context) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L146)
	if r.createdAt != nil {
		return *r.createdAt, nil
	}
	q := r.query.Select("createdAt")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this GithubIssueComment.
func (r *GithubIssueComment) ID(ctx context.Context) (GithubIssueCommentID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response GithubIssueCommentID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *GithubIssueComment) XXX_GraphQLType() string {
	return "GithubIssueComment"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *GithubIssueComment) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *GithubIssueComment) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *GithubIssueComment) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *GithubIssueComment) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = GithubIssueComment{query: selectNode(dag.query, id, "GithubIssueComment")}
	return nil
}

// AsNode returns this GithubIssueComment as a Node.
// This is a local type conversion — no GraphQL call.
func (r *GithubIssueComment) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

type GithubIssueData struct { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L34)
	query *querybuilder.Selection

	author      *string
	baseRef     *string
	body        *string
	diffUrl     *string
	headRef     *string
	id          *GithubIssueDataID
	issueNumber *int
	title       *string
	url         *string
}

func (r *GithubIssueData) WithGraphQLQuery(q *querybuilder.Selection) *GithubIssueData {
	return &GithubIssueData{
		query: q,
	}
}

// Issue author
func (r *GithubIssueData) Author(ctx context.Context) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L37)
	if r.author != nil {
		return *r.author, nil
	}
	q := r.query.Select("author")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Base ref for a pull request
func (r *GithubIssueData) BaseRef(ctx context.Context) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L45)
	if r.baseRef != nil {
		return *r.baseRef, nil
	}
	q := r.query.Select("baseRef")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Issue body content
func (r *GithubIssueData) Body(ctx context.Context) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L41)
	if r.body != nil {
		return *r.body, nil
	}
	q := r.query.Select("body")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// URL for a pull request diff
func (r *GithubIssueData) DiffURL(ctx context.Context) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L47)
	if r.diffUrl != nil {
		return *r.diffUrl, nil
	}
	q := r.query.Select("diffUrl")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Head ref for a pull request
func (r *GithubIssueData) HeadRef(ctx context.Context) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L43)
	if r.headRef != nil {
		return *r.headRef, nil
	}
	q := r.query.Select("headRef")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this GithubIssueData.
func (r *GithubIssueData) ID(ctx context.Context) (GithubIssueDataID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response GithubIssueDataID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *GithubIssueData) XXX_GraphQLType() string {
	return "GithubIssueData"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *GithubIssueData) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *GithubIssueData) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *GithubIssueData) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *GithubIssueData) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = GithubIssueData{query: selectNode(dag.query, id, "GithubIssueData")}
	return nil
}

func (r *GithubIssueData) IssueNumber(ctx context.Context) (int, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L35)
	if r.issueNumber != nil {
		return *r.issueNumber, nil
	}
	q := r.query.Select("issueNumber")

	var response int

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Issue title
func (r *GithubIssueData) Title(ctx context.Context) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L39)
	if r.title != nil {
		return *r.title, nil
	}
	q := r.query.Select("title")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// URL to the issue in Github
func (r *GithubIssueData) URL(ctx context.Context) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L49)
	if r.url != nil {
		return *r.url, nil
	}
	q := r.query.Select("url")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this GithubIssueData as a Node.
// This is a local type conversion — no GraphQL call.
func (r *GithubIssueData) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

type GithubIssueTemplate struct { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L526)
	query *querybuilder.Selection

	content *string
	id      *GithubIssueTemplateID
	name    *string
}

func (r *GithubIssueTemplate) WithGraphQLQuery(q *querybuilder.Selection) *GithubIssueTemplate {
	return &GithubIssueTemplate{
		query: q,
	}
}

func (r *GithubIssueTemplate) Content(ctx context.Context) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L528)
	if r.content != nil {
		return *r.content, nil
	}
	q := r.query.Select("content")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this GithubIssueTemplate.
func (r *GithubIssueTemplate) ID(ctx context.Context) (GithubIssueTemplateID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response GithubIssueTemplateID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *GithubIssueTemplate) XXX_GraphQLType() string {
	return "GithubIssueTemplate"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *GithubIssueTemplate) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *GithubIssueTemplate) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *GithubIssueTemplate) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *GithubIssueTemplate) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = GithubIssueTemplate{query: selectNode(dag.query, id, "GithubIssueTemplate")}
	return nil
}

func (r *GithubIssueTemplate) Name(ctx context.Context) (string, error) { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L527)
	if r.name != nil {
		return *r.name, nil
	}
	q := r.query.Select("name")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this GithubIssueTemplate as a Node.
// This is a local type conversion — no GraphQL call.
func (r *GithubIssueTemplate) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// GithubIssueOpts contains options for Query.GithubIssue
type GithubIssueOpts struct {
	//
	// Github authentication token
	//
	Token *Secret // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L29)
}

// Crate a new GithubIssue object
func (r *Query) GithubIssue(opts ...GithubIssueOpts) *GithubIssue { // github-issue (https://github.com/kpenfound/dag/tree/2b76331a92be6da3fead95305e7bf2a70726c1e6/github-issue/main.go#L26)
	q := r.query.Select("githubIssue")
	for i := len(opts) - 1; i >= 0; i-- {
		// `token` optional argument
		if !querybuilder.IsZeroValue(opts[i].Token) {
			q = q.Arg("token", opts[i].Token)
		}
	}

	return &GithubIssue{
		query: q,
	}
}
