// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type GithubRelease
func (r *Binding) AsGithubRelease() *GithubRelease { // github-release (https://github.com/kpenfound/jpadams-github-release/tree/c6081b3210407d5ea49fce8874c5104afa8373cb/main.go#L12)
	q := r.query.Select("asGithubRelease")

	return &GithubRelease{
		query: q,
	}
}

// Create or update a binding of type GithubRelease in the environment
func (r *Env) WithGithubReleaseInput(name string, value *GithubRelease, description string) *Env { // github-release (https://github.com/kpenfound/jpadams-github-release/tree/c6081b3210407d5ea49fce8874c5104afa8373cb/main.go#L12)
	assertNotNil("value", value)
	q := r.query.Select("withGithubReleaseInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired GithubRelease output to be assigned in the environment
func (r *Env) WithGithubReleaseOutput(name string, description string) *Env { // github-release (https://github.com/kpenfound/jpadams-github-release/tree/c6081b3210407d5ea49fce8874c5104afa8373cb/main.go#L12)
	q := r.query.Select("withGithubReleaseOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type GithubRelease struct { // github-release (https://github.com/kpenfound/jpadams-github-release/tree/c6081b3210407d5ea49fce8874c5104afa8373cb/main.go#L12)
	query *querybuilder.Selection

	create *string
	id     *GithubReleaseID
}

func (r *GithubRelease) WithGraphQLQuery(q *querybuilder.Selection) *GithubRelease {
	return &GithubRelease{
		query: q,
	}
}

// GithubReleaseCreateOpts contains options for GithubRelease.Create
type GithubReleaseCreateOpts struct {
	Assets *Directory // github-release (https://github.com/kpenfound/jpadams-github-release/tree/c6081b3210407d5ea49fce8874c5104afa8373cb/main.go#L21)

	Notes string // github-release (https://github.com/kpenfound/jpadams-github-release/tree/c6081b3210407d5ea49fce8874c5104afa8373cb/main.go#L23)

	Draft bool // github-release (https://github.com/kpenfound/jpadams-github-release/tree/c6081b3210407d5ea49fce8874c5104afa8373cb/main.go#L25)

	Latest bool // github-release (https://github.com/kpenfound/jpadams-github-release/tree/c6081b3210407d5ea49fce8874c5104afa8373cb/main.go#L27)

	Prerelease bool // github-release (https://github.com/kpenfound/jpadams-github-release/tree/c6081b3210407d5ea49fce8874c5104afa8373cb/main.go#L29)
}

func (r *GithubRelease) Create(ctx context.Context, repo string, tag string, title string, token *Secret, opts ...GithubReleaseCreateOpts) (string, error) { // github-release (https://github.com/kpenfound/jpadams-github-release/tree/c6081b3210407d5ea49fce8874c5104afa8373cb/main.go#L14)
	assertNotNil("token", token)
	if r.create != nil {
		return *r.create, nil
	}
	q := r.query.Select("create")
	for i := len(opts) - 1; i >= 0; i-- {
		// `assets` optional argument
		if !querybuilder.IsZeroValue(opts[i].Assets) {
			q = q.Arg("assets", opts[i].Assets)
		}
		// `notes` optional argument
		if !querybuilder.IsZeroValue(opts[i].Notes) {
			q = q.Arg("notes", opts[i].Notes)
		}
		// `draft` optional argument
		if !querybuilder.IsZeroValue(opts[i].Draft) {
			q = q.Arg("draft", opts[i].Draft)
		}
		// `latest` optional argument
		if !querybuilder.IsZeroValue(opts[i].Latest) {
			q = q.Arg("latest", opts[i].Latest)
		}
		// `prerelease` optional argument
		if !querybuilder.IsZeroValue(opts[i].Prerelease) {
			q = q.Arg("prerelease", opts[i].Prerelease)
		}
	}
	q = q.Arg("repo", repo)
	q = q.Arg("tag", tag)
	q = q.Arg("title", title)
	q = q.Arg("token", token)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this GithubRelease.
func (r *GithubRelease) ID(ctx context.Context) (GithubReleaseID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response GithubReleaseID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *GithubRelease) XXX_GraphQLType() string {
	return "GithubRelease"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *GithubRelease) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *GithubRelease) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *GithubRelease) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *GithubRelease) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = GithubRelease{query: selectNode(dag.query, id, "GithubRelease")}
	return nil
}

// AsNode returns this GithubRelease as a Node.
// This is a local type conversion — no GraphQL call.
func (r *GithubRelease) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

func (r *Query) GithubRelease() *GithubRelease { // github-release (https://github.com/kpenfound/jpadams-github-release/tree/c6081b3210407d5ea49fce8874c5104afa8373cb/main.go#L12)
	q := r.query.Select("githubRelease")

	return &GithubRelease{
		query: q,
	}
}
