// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// A unique identifier for an object.
type GreetingsID = ID // greetings (../../../:0:0)

type Greetings struct { // greetings (../../../:0:0)
	query *querybuilder.Selection

	check               *string
	debugBrokenTestsPr  *Void
	debugTests          *string
	developPullRequest  *string
	developReview       *string
	id                  *GreetingsID
	lint                *string
	pullRequestFeedback *Void
	pullRequestReview   *Void
	release             *string
	test                *string
}

func (r *Greetings) WithGraphQLQuery(q *querybuilder.Selection) *Greetings {
	return &Greetings{
		query: q,
	}
}

// Build the backend and frontend for a specified environment
func (r *Greetings) Build() *Directory {
	q := r.query.Select("build")

	return &Directory{
		query: q,
	}
}

// GreetingsCheckOpts contains options for Greetings.Check
type GreetingsCheckOpts struct {
	// Github token with permissions to comment on the pull request
	GithubToken *Secret
	// git commit in github
	Commit string
	// The model to use to debug debug tests
	Model string
}

// Run the CI Checks for the project
func (r *Greetings) Check(ctx context.Context, opts ...GreetingsCheckOpts) (string, error) {
	if r.check != nil {
		return *r.check, nil
	}
	q := r.query.Select("check")
	for i := len(opts) - 1; i >= 0; i-- {
		// `githubToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubToken) {
			q = q.Arg("githubToken", opts[i].GithubToken)
		}
		// `commit` optional argument
		if !querybuilder.IsZeroValue(opts[i].Commit) {
			q = q.Arg("commit", opts[i].Commit)
		}
		// `model` optional argument
		if !querybuilder.IsZeroValue(opts[i].Model) {
			q = q.Arg("model", opts[i].Model)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GreetingsDebugBrokenTestsPrOpts contains options for Greetings.DebugBrokenTestsPr
type GreetingsDebugBrokenTestsPrOpts struct {
	// The model to use to debug debug tests
	// +default = "claude-sonnet-4-0"
	Model string
}

// Debug broken tests on a pull request and comment fix suggestions
func (r *Greetings) DebugBrokenTestsPr(ctx context.Context, githubToken *Secret, commit string, opts ...GreetingsDebugBrokenTestsPrOpts) error {
	assertNotNil("githubToken", githubToken)
	if r.debugBrokenTestsPr != nil {
		return nil
	}
	q := r.query.Select("debugBrokenTestsPr")
	for i := len(opts) - 1; i >= 0; i-- {
		// `model` optional argument
		if !querybuilder.IsZeroValue(opts[i].Model) {
			q = q.Arg("model", opts[i].Model)
		}
	}
	q = q.Arg("githubToken", githubToken)
	q = q.Arg("commit", commit)

	return q.Execute(ctx)
}

// GreetingsDebugTestsOpts contains options for Greetings.DebugTests
type GreetingsDebugTestsOpts struct {
	// The model to use to debug debug tests
	// +default = "claude-sonnet-4-0"
	Model string
}

// Debug broken tests. Returns a unified diff of the test fixes
func (r *Greetings) DebugTests(ctx context.Context, opts ...GreetingsDebugTestsOpts) (string, error) {
	if r.debugTests != nil {
		return *r.debugTests, nil
	}
	q := r.query.Select("debugTests")
	for i := len(opts) - 1; i >= 0; i-- {
		// `model` optional argument
		if !querybuilder.IsZeroValue(opts[i].Model) {
			q = q.Arg("model", opts[i].Model)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GreetingsDevelopOpts contains options for Greetings.Develop
type GreetingsDevelopOpts struct {
	// The model to use to complete the assignment
	// +default = "claude-sonnet-4-0"
	Model string
}

// Complete an assignment for the greetings project and get back the completed work
func (r *Greetings) Develop(assignment string, opts ...GreetingsDevelopOpts) *Directory {
	q := r.query.Select("develop")
	for i := len(opts) - 1; i >= 0; i-- {
		// `model` optional argument
		if !querybuilder.IsZeroValue(opts[i].Model) {
			q = q.Arg("model", opts[i].Model)
		}
	}
	q = q.Arg("assignment", assignment)

	return &Directory{
		query: q,
	}
}

// GreetingsDevelopFeedbackOpts contains options for Greetings.DevelopFeedback
type GreetingsDevelopFeedbackOpts struct {
	// The model to use to complete the assignment
	// +default = "claude-sonnet-4-0"
	Model string
}

// Agent to develop changes based on feedback on changes made in a Directory
func (r *Greetings) DevelopFeedback(source *Directory, assignment string, diff string, feedback string, opts ...GreetingsDevelopFeedbackOpts) *Directory {
	assertNotNil("source", source)
	q := r.query.Select("developFeedback")
	for i := len(opts) - 1; i >= 0; i-- {
		// `model` optional argument
		if !querybuilder.IsZeroValue(opts[i].Model) {
			q = q.Arg("model", opts[i].Model)
		}
	}
	q = q.Arg("source", source)
	q = q.Arg("assignment", assignment)
	q = q.Arg("diff", diff)
	q = q.Arg("feedback", feedback)

	return &Directory{
		query: q,
	}
}

// GreetingsDevelopPullRequestOpts contains options for Greetings.DevelopPullRequest
type GreetingsDevelopPullRequestOpts struct {
	// The model to use to complete the assignment
	// +default = "claude-sonnet-4-0"
	Model string
}

// Develop changes based on a Github issue and open a pull request
func (r *Greetings) DevelopPullRequest(ctx context.Context, githubToken *Secret, issueId int, opts ...GreetingsDevelopPullRequestOpts) (string, error) {
	assertNotNil("githubToken", githubToken)
	if r.developPullRequest != nil {
		return *r.developPullRequest, nil
	}
	q := r.query.Select("developPullRequest")
	for i := len(opts) - 1; i >= 0; i-- {
		// `model` optional argument
		if !querybuilder.IsZeroValue(opts[i].Model) {
			q = q.Arg("model", opts[i].Model)
		}
	}
	q = q.Arg("githubToken", githubToken)
	q = q.Arg("issueId", issueId)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GreetingsDevelopReviewOpts contains options for Greetings.DevelopReview
type GreetingsDevelopReviewOpts struct {
	// The model to use to complete the assignment
	// +default = "claude-sonnet-4-0"
	Model string
}

// Agent to review changes made in a Directory
func (r *Greetings) DevelopReview(ctx context.Context, source *Directory, assignment string, diff string, opts ...GreetingsDevelopReviewOpts) (string, error) {
	assertNotNil("source", source)
	if r.developReview != nil {
		return *r.developReview, nil
	}
	q := r.query.Select("developReview")
	for i := len(opts) - 1; i >= 0; i-- {
		// `model` optional argument
		if !querybuilder.IsZeroValue(opts[i].Model) {
			q = q.Arg("model", opts[i].Model)
		}
	}
	q = q.Arg("source", source)
	q = q.Arg("assignment", assignment)
	q = q.Arg("diff", diff)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this Greetings.
func (r *Greetings) ID(ctx context.Context) (GreetingsID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response GreetingsID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Greetings) XXX_GraphQLType() string {
	return "Greetings"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Greetings) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Greetings) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Greetings) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Greetings) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Greetings{query: selectNode(dag.query, id, "Greetings")}
	return nil
}

// Lint the Go code in the project
func (r *Greetings) Lint(ctx context.Context) (string, error) {
	if r.lint != nil {
		return *r.lint, nil
	}
	q := r.query.Select("lint")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GreetingsPullRequestFeedbackOpts contains options for Greetings.PullRequestFeedback
type GreetingsPullRequestFeedbackOpts struct {
	// The model to use to complete the assignment
	// +default = "claude-sonnet-4-0"
	Model string
}

// Receive feedback on an open pull request via slash command
func (r *Greetings) PullRequestFeedback(ctx context.Context, githubToken *Secret, issueId int, feedback string, opts ...GreetingsPullRequestFeedbackOpts) error {
	assertNotNil("githubToken", githubToken)
	if r.pullRequestFeedback != nil {
		return nil
	}
	q := r.query.Select("pullRequestFeedback")
	for i := len(opts) - 1; i >= 0; i-- {
		// `model` optional argument
		if !querybuilder.IsZeroValue(opts[i].Model) {
			q = q.Arg("model", opts[i].Model)
		}
	}
	q = q.Arg("githubToken", githubToken)
	q = q.Arg("issueId", issueId)
	q = q.Arg("feedback", feedback)

	return q.Execute(ctx)
}

// GreetingsPullRequestReviewOpts contains options for Greetings.PullRequestReview
type GreetingsPullRequestReviewOpts struct {
	// The model to use to complete the assignment
	// +default = "claude-sonnet-4-0"
	Model string
}

// Review an open pull request via slash command
func (r *Greetings) PullRequestReview(ctx context.Context, githubToken *Secret, issueId int, opts ...GreetingsPullRequestReviewOpts) error {
	assertNotNil("githubToken", githubToken)
	if r.pullRequestReview != nil {
		return nil
	}
	q := r.query.Select("pullRequestReview")
	for i := len(opts) - 1; i >= 0; i-- {
		// `model` optional argument
		if !querybuilder.IsZeroValue(opts[i].Model) {
			q = q.Arg("model", opts[i].Model)
		}
	}
	q = q.Arg("githubToken", githubToken)
	q = q.Arg("issueId", issueId)

	return q.Execute(ctx)
}

// Create a GitHub release
func (r *Greetings) Release(ctx context.Context, tag string, ghToken *Secret) (string, error) {
	assertNotNil("ghToken", ghToken)
	if r.release != nil {
		return *r.release, nil
	}
	q := r.query.Select("release")
	q = q.Arg("tag", tag)
	q = q.Arg("ghToken", ghToken)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Serve the backend and frontend to 8080 and 8081 respectively
func (r *Greetings) Serve() *Service {
	q := r.query.Select("serve")

	return &Service{
		query: q,
	}
}

// Run unit tests for the project
func (r *Greetings) Test(ctx context.Context) (string, error) {
	if r.test != nil {
		return *r.test, nil
	}
	q := r.query.Select("test")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GreetingsOpts contains options for Query.Greetings
type GreetingsOpts struct {
	Source *Directory

	// Default: "github.com/kpenfound/greetings-api"
	Repo string

	// Default: "kylepenfound/greetings-api:latest"
	Image string

	// Default: "dagger-demo"
	App string
}

func (r *Query) Greetings(opts ...GreetingsOpts) *Greetings { // greetings (../../../:0:0)
	q := r.query.Select("greetings")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `repo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Repo) {
			q = q.Arg("repo", opts[i].Repo)
		}
		// `image` optional argument
		if !querybuilder.IsZeroValue(opts[i].Image) {
			q = q.Arg("image", opts[i].Image)
		}
		// `app` optional argument
		if !querybuilder.IsZeroValue(opts[i].App) {
			q = q.Arg("app", opts[i].App)
		}
	}

	return &Greetings{
		query: q,
	}
}
