// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Proxy
func (r *Binding) AsProxy() *Proxy { // proxy (../../../:0:0)
	q := r.query.Select("asProxy")

	return &Proxy{
		query: q,
	}
}

// Create or update a binding of type Proxy in the environment
func (r *Env) WithProxyInput(name string, value *Proxy, description string) *Env { // proxy (../../../:0:0)
	assertNotNil("value", value)
	q := r.query.Select("withProxyInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Proxy output to be assigned in the environment
func (r *Env) WithProxyOutput(name string, description string) *Env { // proxy (../../../:0:0)
	q := r.query.Select("withProxyOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Forwards multiple services into a single service with multiple ports
type Proxy struct { // proxy (../../../:0:0)
	query *querybuilder.Selection

	id *ProxyID
}
type WithProxyFunc func(r *Proxy) *Proxy

// With calls the provided function with current Proxy.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *Proxy) With(f WithProxyFunc) *Proxy {
	return f(r)
}

func (r *Proxy) WithGraphQLQuery(q *querybuilder.Selection) *Proxy {
	return &Proxy{
		query: q,
	}
}

// An OCI-compatible container, also known as a Docker container.
func (r *Proxy) Ctr() *Container { // proxy (../../../:0:0)
	q := r.query.Select("ctr")

	return &Container{
		query: q,
	}
}

// A unique identifier for this Proxy.
func (r *Proxy) ID(ctx context.Context) (ProxyID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ProxyID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Proxy) XXX_GraphQLType() string {
	return "Proxy"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Proxy) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Proxy) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Proxy) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Proxy) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Proxy{query: selectNode(dag.query, id, "Proxy")}
	return nil
}

// Get the proxy Service
func (r *Proxy) Service() *Service { // proxy (../../../:0:0)
	q := r.query.Select("service")

	return &Service{
		query: q,
	}
}

// ProxyWithServiceOpts contains options for Proxy.WithService
type ProxyWithServiceOpts struct {
	IsTCP bool // proxy (../../../:0:0)
}

// Add a service to proxy
func (r *Proxy) WithService(service *Service, name string, frontend int, backend int, opts ...ProxyWithServiceOpts) *Proxy { // proxy (../../../:0:0)
	assertNotNil("service", service)
	q := r.query.Select("withService")
	for i := len(opts) - 1; i >= 0; i-- {
		// `isTcp` optional argument
		if !querybuilder.IsZeroValue(opts[i].IsTCP) {
			q = q.Arg("isTcp", opts[i].IsTCP)
		}
	}
	q = q.Arg("service", service)
	q = q.Arg("name", name)
	q = q.Arg("frontend", frontend)
	q = q.Arg("backend", backend)

	return &Proxy{
		query: q,
	}
}

// AsNode returns this Proxy as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Proxy) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// ProxyOpts contains options for Query.Proxy
type ProxyOpts struct {
	//
	// An OCI-compatible container, also known as a Docker container.
	//
	Ctr *Container // proxy (../../../:0:0)
}

// Forwards multiple services into a single service with multiple ports
func (r *Query) Proxy(opts ...ProxyOpts) *Proxy { // proxy (../../../:0:0)
	q := r.query.Select("proxy")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ctr` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ctr) {
			q = q.Arg("ctr", opts[i].Ctr)
		}
	}

	return &Proxy{
		query: q,
	}
}
