from typing import Annotated

import dagger
from dagger import DefaultPath, check, dag, function, generate, object_type, up


@object_type
class GreetingsApi:
    source: Annotated[dagger.Directory, DefaultPath("/")]

    @function
    def go_build(self) -> dagger.Changeset:
        """Builds the go project"""
        build = (
            dag.container()
            .from_("golang:latest")
            .with_mounted_directory("/app", self.source)
            .with_workdir("/app")
            .with_exec(["go", "build", "./..."])
            .directory("/app")
        )

        """Returns any new files generated by the build"""
        return build.changes(self.source)

    @function
    async def go_test(self) -> str:
        """Test the go project"""
        return await (
            dag.container()
            .from_("golang:latest")
            .with_mounted_directory("/app", self.source)
            .with_workdir("/app")
            .with_exec(["go", "test", "./..."])
            .stdout()
        )

    @function
    @check
    async def check_test(self) -> None:
        """Check the go tests are passing"""
        await self.go_test()

    @function
    @generate
    def go_fmt(self) -> dagger.Changeset:
        """Go fmt"""
        fmt = (
            dag.container()
            .from_("golang:latest")
            .with_mounted_directory("/app", self.source)
            .with_workdir("/app")
            .with_exec(["go", "fmt", "./..."])
            .directory("/app")
        )

        """Returns any changes from fmt"""
        return fmt.changes(self.source)

    @function
    @check
    async def check_fmt(self) -> None:
        """Check go is formatted correctly"""
        fmt_empty = await self.go_fmt().is_empty()
        if not fmt_empty:
            raise Exception("go needs formatting")

    @function
    @up
    def api_service(self) -> dagger.Service:
        """Serves the API"""
        return self.api_container().as_service(use_entrypoint=True)

    @function
    @up
    def web_service(self) -> dagger.Service:
        """Serves the frontend"""
        return (
            dag.container()
            .from_("nginx:latest")
            .with_new_file(
                "/etc/nginx/conf.d/default.conf",
                """
                server {
                    listen 8081;
                    root /website;

                    location / {
                    }
                }
            """,
            )
            .with_exposed_port(8081)
            .with_mounted_directory("/website", self.source.directory("website"))
            .as_service(use_entrypoint=True)
        )

    @function
    def api_container(self) -> dagger.Container:
        """Returns the API container"""
        return (
            dag.container()
            .from_("cgr.dev/chainguard/wolfi-base:latest")
            .with_mounted_directory("/usr/bin", self.go_build().layer())
            .with_entrypoint(["/usr/bin/greetings-api"])
            .with_exposed_port(8080)
        )
