from typing import Annotated

import dagger
from dagger import DefaultPath, check, dag, function, generate, object_type, up


@object_type
class GreetingsApi:
    source: Annotated[dagger.Directory, DefaultPath("/")]

    @function
    def go_build(self) -> dagger.Changeset:
        """Builds the go project"""
        build = (
            dag.container()
            .from_("golang:latest")
            .with_mounted_directory("/app", self.source)
            .with_workdir("/app")
            .with_exec(["go", "build", "./..."])
            .directory("/app")
        )

        """Returns any new files generated by the build"""
        return build.changes(self.source)

    @function
    @check
    async def go_test(self) -> None:
        """Test the go project"""
        await (
            dag.container()
            .from_("golang:latest")
            .with_mounted_directory("/app", self.source)
            .with_workdir("/app")
            .with_exec(["go", "test", "./..."])
            .sync()
        )

    @function
    @generate
    def go_fmt(self) -> dagger.Changeset:
        """Go fmt"""
        fmt = (
            dag.container()
            .from_("golang:latest")
            .with_mounted_directory("/app", self.source)
            .with_workdir("/app")
            .with_exec(["go", "fmt", "./..."])
            .directory("/app")
        )

        """Returns any changes from fmt"""
        return fmt.changes(self.source)

    @function
    @up
    def api_service(self) -> dagger.Service:
        """Serves the API"""
        return self.api_container().as_service(use_entrypoint=True)

    @function
    @up
    def web_service(self) -> dagger.Service:
        """Serves the frontend"""
        return self.frontend_container().as_service(use_entrypoint=True)

    @function
    def api_container(self) -> dagger.Container:
        """Returns the API container"""
        return (
            dag.container()
            .from_("cgr.dev/chainguard/wolfi-base:latest")
            .with_mounted_directory("/usr/bin", self.go_build().layer())
            .with_entrypoint(["/usr/bin/greetings-api"])
            .with_exposed_port(8080)
        )

    @function
    def frontend_container(self) -> dagger.Container:
        """Returns the frontend container"""
        return (
            dag.container()
            .from_("nginx:latest")
            .with_mounted_directory(
                "/usr/share/nginx/html", self.source.directory("website")
            )
        )
