name = "greetings"
engineVersion = "v0.20.6"
disableDefaultFunctionCaching = true

[runtime]
  source = "go"

[[dependencies]]
  name = "backend"
  source = "../backend"

[[dependencies]]
  name = "frontend"
  source = "../frontend"
