name = "greetings"
engineVersion = "v0.20.6"
source = "../.."
disableDefaultFunctionCaching = true

[runtime]
  source = "go"

[[dependencies]]
  name = "backend"
  source = "../../backend"

[[dependencies]]
  name = "frontend"
  source = "../../frontend"

[[dependencies]]
  name = "github-issue"
  source = "github.com/kpenfound/dag/github-issue@main"
  pin = "2b76331a92be6da3fead95305e7bf2a70726c1e6"

[[dependencies]]
  name = "github-release"
  source = "github.com/kpenfound/jpadams-github-release@c6081b3210407d5ea49fce8874c5104afa8373cb"
  pin = "c6081b3210407d5ea49fce8874c5104afa8373cb"

[[dependencies]]
  name = "proxy"
  source = "github.com/kpenfound/dagger-modules/proxy@proxy/v0.2.5"
  pin = "3e9129a119151eb122e5fe380bd2d4313d8fc001"

[[dependencies]]
  name = "code-workspace"
  source = "../../workspace"
