// AUTO-GENERATED — DO NOT EDIT.
// Generated by Dagger TypeScript SDK introspector (cmd/codegen generate-entrypoint).

import { Context, Error as DaggerError, FunctionCachePolicy, TypeDefKind, connection, dag, getRegisteredClass } from "@dagger.io/dagger"
import * as __dagger from "@dagger.io/dagger"
import * as telemetry from "@dagger.io/dagger/telemetry"
import { Frontend } from "./src/index"

// Load a core/dependency object from its ID via node(id:) and wrap it in the
// matching generated client class. Mirrors the SDK runtime loader; replaces the
// retired load<Type>FromID API (removed in #12041). Some core type names
// collide with JS builtins and get a trailing "_" (e.g. "Module" -> Module_).
function __loadCoreObject(id: string, typeName: string): any {
  const cls =
    (__dagger as any)[typeName] ?? (__dagger as any)[typeName + "_"]
  if (!cls) {
    throw new Error(`generated client class not found for core type: ${typeName}`)
  }
  return new cls(new Context().selectNode(id, typeName))
}

function formatError(e: unknown): DaggerError {
  if (e instanceof Error) {
    let error = dag.error(e.message)
    const ext = (e as { extensions?: Record<string, unknown> }).extensions
    if (ext) {
      for (const [k, v] of Object.entries(ext)) {
        if (v !== "" && v !== undefined && v !== null) {
          error = error.withValue(
            k,
            JSON.stringify(v) as string & { __JSON: never },
          )
        }
      }
    }
    return error
  }
  try {
    return dag.error(JSON.stringify(e))
  } catch {
    return dag.error(String(e))
  }
}

function rebuildFrontend(state: any): Frontend {
  const __obj = Object.assign(Object.create(Frontend.prototype), state ?? {})
  if (state) {
    if (state["source"] !== undefined && state["source"] !== null) {
      __obj["source"] = __loadCoreObject(state["source"], "Directory")
    }
  }
  return __obj
}

async function serializeFrontend(__obj: Frontend): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  if ((__obj as any)["source"] !== undefined && (__obj as any)["source"] !== null) {
    __state["source"] = await ((__obj as any)["source"]).id()
  }
  return __state
}



async function register(): Promise<string> {
  let mod = dag.module_()
  mod = mod.withDescription("A generated module for Frontend functions")
  let obj_Frontend = dag.typeDef().withObject("Frontend", { sourceMap: dag.sourceMap("src/index.ts", 15, 14) })
  obj_Frontend = obj_Frontend.withFunction(dag.function_("build", dag.typeDef().withObject("Directory")).withSourceMap(dag.sourceMap("src/index.ts", 24, 3)))
  obj_Frontend = obj_Frontend.withFunction(dag.function_("serve", dag.typeDef().withObject("Service")).withSourceMap(dag.sourceMap("src/index.ts", 30, 3)).withUp())
  obj_Frontend = obj_Frontend.withField("source", dag.typeDef().withObject("Directory"), { sourceMap: dag.sourceMap("src/index.ts", 17, 3) })
  obj_Frontend = obj_Frontend.withConstructor(dag.function_("", obj_Frontend).withArg("source", dag.typeDef().withObject("Directory"), { defaultPath: "/website", sourceMap: dag.sourceMap("src/index.ts", 19, 54) }))
  mod = mod.withObject(obj_Frontend)
  return await mod.id()
}

async function invoke(
  parentName: string,
  fnName: string,
  parentJson: any,
  args: Record<string, any>,
): Promise<any> {
  switch (parentName) {
    case "Frontend": {
      switch (fnName) {

        case "": {
          const __arg_source = args["source"] === undefined || args["source"] === null ? args["source"] : __loadCoreObject(args["source"], "Directory")
          const __result = await new Frontend(__arg_source) as unknown as Frontend
          return await serializeFrontend(__result)
        }

        case "build": {
          const __parent = rebuildFrontend(parentJson)
          const __result = await __parent.build()
          return await (__result).id()
        }

        case "serve": {
          const __parent = rebuildFrontend(parentJson)
          const __result = await __parent.serve()
          return await (__result).id()
        }
        default:
          throw new Error(`unknown function ${fnName} on Frontend`)
      }
    }
    default:
      throw new Error(`unknown object ${parentName}`)
  }
}

async function dispatch() {
  await connection(async () => {
    const fnCall = dag.currentFunctionCall()
    const parentName = await fnCall.parentName()

    if (parentName === "") {
      const id = await register()
      await fnCall.returnValue(JSON.stringify(id) as string & { __JSON: never })
      return
    }

    const fnName = await fnCall.name()
    const parentJson = JSON.parse(await fnCall.parent())
    const fnArgs = await fnCall.inputArgs()

    const args: Record<string, any> = {}
    for (const arg of fnArgs) {
      args[await arg.name()] = JSON.parse(await arg.value())
    }

    try {
      const result = await invoke(parentName, fnName, parentJson, args)
      const out = result === undefined || result === null ? "null" : JSON.stringify(result)
      await fnCall.returnValue(out as string & { __JSON: never })
    } catch (e: unknown) {
      await fnCall.returnError(formatError(e))
      process.exit(1)
    }
  }, { LogOutput: process.stdout })
}

dispatch().catch((e) => {
  console.error(e)
  process.exit(2)
})