// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"backend/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Backend) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Binary *dagger.File
	}
	concrete.Binary = r.Binary
	return json.Marshal(&concrete)
}

func (r *Backend) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Binary *dagger.File
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Binary = concrete.Binary
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Backend":
		switch fnName {
		case "Container":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Backend).Container(&parent), nil
		case "GoTestBase":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Backend).GoTestBase(&parent), nil
		case "Serve":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Backend).Serve(&parent), nil
		case "":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var binary *dagger.File
			if inputArgs["binary"] != nil {
				err = json.Unmarshal([]byte(inputArgs["binary"]), &binary)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg binary", err))
				}
			}
			return New(binary), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithObject(
				dag.TypeDef().WithObject("Backend", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 7, 6)}).
					WithFunction(
						dag.Function("Container",
							dag.TypeDef().WithObject("Container")).
							WithDescription("Get a container ready to run the backend").
							WithSourceMap(dag.SourceMap("main.go", 23, 1))).
					WithFunction(
						dag.Function("GoTestBase",
							dag.TypeDef().WithObject("Container")).
							WithDescription("A Go container with the backend API running as a bound service, for the go\nmodule's `base` setting (dagger.toml: [modules.go.settings] base =\n\"backend:go-test-base\").\n\nThe e2e tests in e2e_test.go need a server to talk to, which the go\ntoolchain has no way to start. Handing it a base container with the service\nalready bound lets its own test check run them; without this they skip, and\na skip reports the same as a pass.\n\nDeliberately no workdir, source mount or cache mounts: the go module adds its\nown on top. This is only an image plus a service and the address to reach it.\nThe binding survives into every command the toolchain derives from this.\n\nThe image matches the toolchain's own default rather than the version in\ngo.mod. It has to: this base also builds the toolchain's helper binaries,\nwhose go.mod requires 1.26, so an older image fails before any test runs.").
							WithSourceMap(dag.SourceMap("main.go", 55, 1))).
					WithFunction(
						dag.Function("Serve",
							dag.TypeDef().WithObject("Service")).
							WithDescription("Get a Service to run the backend").
							WithSourceMap(dag.SourceMap("main.go", 35, 1)).
							WithUp()).
					WithField("Binary", dag.TypeDef().WithObject("File"), dagger.TypeDefWithFieldOpts{Description: "The compiled backend binary", SourceMap: dag.SourceMap("main.go", 9, 2)}).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("Backend")).
							WithSourceMap(dag.SourceMap("main.go", 12, 1)).
							WithArg("binary", dag.TypeDef().WithObject("File"), dagger.FunctionWithArgOpts{Description: "The compiled backend binary. dagger.toml wires this to the go module's\nbuild of the root package.", SourceMap: dag.SourceMap("main.go", 15, 2)}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
