// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Backend struct { // backend (../../.dagger/backend/main.go:11:6)
	query *querybuilder.Selection

	checkDirectory *string
	id             *BackendID
}

func (r *Backend) WithGraphQLQuery(q *querybuilder.Selection) *Backend {
	return &Backend{
		query: q,
	}
}

// BackendBinaryOpts contains options for Backend.Binary
type BackendBinaryOpts struct {
	Arch string // backend (../../.dagger/backend/main.go:75:2)
}

// Return the compiled backend binary for a particular architecture
func (r *Backend) Binary(opts ...BackendBinaryOpts) *File { // backend (../../.dagger/backend/main.go:73:1)
	q := r.query.Select("binary")
	for i := len(opts) - 1; i >= 0; i-- {
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
	}

	return &File{
		query: q,
	}
}

// BackendBuildOpts contains options for Backend.Build
type BackendBuildOpts struct {
	Arch string // backend (../../.dagger/backend/main.go:60:2)
}

// Build the backend
func (r *Backend) Build(opts ...BackendBuildOpts) *Directory { // backend (../../.dagger/backend/main.go:58:1)
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
	}

	return &Directory{
		query: q,
	}
}

// Stateless checker
func (r *Backend) CheckDirectory(ctx context.Context, source *Directory) (string, error) { // backend (../../.dagger/backend/main.go:129:1)
	assertNotNil("source", source)
	if r.checkDirectory != nil {
		return *r.checkDirectory, nil
	}
	q := r.query.Select("checkDirectory")
	q = q.Arg("source", source)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// BackendContainerOpts contains options for Backend.Container
type BackendContainerOpts struct {
	Arch string // backend (../../.dagger/backend/main.go:84:2)
}

// Get a container ready to run the backend
func (r *Backend) Container(opts ...BackendContainerOpts) *Container { // backend (../../.dagger/backend/main.go:82:1)
	q := r.query.Select("container")
	for i := len(opts) - 1; i >= 0; i-- {
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
	}

	return &Container{
		query: q,
	}
}

// Formatter
func (r *Backend) Format() *Directory { // backend (../../.dagger/backend/main.go:50:1)
	q := r.query.Select("format")

	return &Directory{
		query: q,
	}
}

// Stateless formatter
func (r *Backend) FormatDirectory(source *Directory) *Directory { // backend (../../.dagger/backend/main.go:150:1)
	assertNotNil("source", source)
	q := r.query.Select("formatDirectory")
	q = q.Arg("source", source)

	return &Directory{
		query: q,
	}
}

// Stateless formatter
func (r *Backend) FormatFile(source *Directory, path string) *Directory { // backend (../../.dagger/backend/main.go:159:1)
	assertNotNil("source", source)
	q := r.query.Select("formatFile")
	q = q.Arg("source", source)
	q = q.Arg("path", path)

	return &Directory{
		query: q,
	}
}

// A Go container with the backend API running as a bound service, for the go
// module's `base` setting (dagger.toml: [modules.go.settings] base =
// "backend:go-test-base").
//
// The e2e tests in e2e_test.go need a server to talk to, which the go
// toolchain has no way to start. Handing it a base container with the service
// already bound lets its own test check run them; without this they skip, and
// a skip reports the same as a pass.
//
// Deliberately no workdir, source mount or cache mounts: the go module adds its
// own on top. This is only an image plus a service and the address to reach it.
// The binding survives into every command the toolchain derives from this.
//
// The image matches the toolchain's own default rather than the version in
// go.mod. It has to: this base also builds the toolchain's helper binaries,
// whose go.mod requires 1.26, so an older image fails before any test runs.
func (r *Backend) GoTestBase() *Container { // backend (../../.dagger/backend/main.go:121:1)
	q := r.query.Select("goTestBase")

	return &Container{
		query: q,
	}
}

// A unique identifier for this Backend.
func (r *Backend) ID(ctx context.Context) (BackendID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response BackendID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Backend) XXX_GraphQLType() string {
	return "Backend"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Backend) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Backend) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Backend) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// Get a Service to run the backend
func (r *Backend) Serve() *Service { // backend (../../.dagger/backend/main.go:101:1)
	q := r.query.Select("serve")

	return &Service{
		query: q,
	}
}

func (r *Backend) Source() *Directory { // backend (../../.dagger/backend/main.go:12:2)
	q := r.query.Select("source")

	return &Directory{
		query: q,
	}
}

// AsNode returns this Backend as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Backend) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// BackendOpts contains options for Query.Backend
type BackendOpts struct {
	Source *Directory // backend (../../.dagger/backend/main.go:19:2)
}

func (r *Query) Backend(opts ...BackendOpts) *Backend { // backend (../../.dagger/backend/main.go:15:1)
	q := r.query.Select("backend")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	return &Backend{
		query: q,
	}
}
