// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Backend struct { // backend (../../../../../.dagger/modules/backend/main.go:7:6)
	query *querybuilder.Selection

	id *ID
}

func (r *Backend) WithGraphQLQuery(q *querybuilder.Selection) *Backend {
	return &Backend{
		query: q,
	}
}

// The compiled backend binary
func (r *Backend) Binary() *File { // backend (../../../../../.dagger/modules/backend/main.go:9:2)
	q := r.query.Select("binary")

	return &File{
		query: q,
	}
}

// Get a container ready to run the backend
func (r *Backend) Container() *Container { // backend (../../../../../.dagger/modules/backend/main.go:23:1)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// A Go container with the backend API running as a bound service, for the go
// module's `base` setting (dagger.toml: [modules.go.settings] base =
// "backend:go-test-base").
//
// The e2e tests in e2e_test.go need a server to talk to, which the go
// toolchain has no way to start. Handing it a base container with the service
// already bound lets its own test check run them; without this they skip, and
// a skip reports the same as a pass.
//
// Deliberately no workdir, source mount or cache mounts: the go module adds its
// own on top. This is only an image plus a service and the address to reach it.
// The binding survives into every command the toolchain derives from this.
//
// The image matches the toolchain's own default rather than the version in
// go.mod. It has to: this base also builds the toolchain's helper binaries,
// whose go.mod requires 1.26, so an older image fails before any test runs.
func (r *Backend) GoTestBase() *Container { // backend (../../../../../.dagger/modules/backend/main.go:55:1)
	q := r.query.Select("goTestBase")

	return &Container{
		query: q,
	}
}

// A unique identifier for this Backend.
func (r *Backend) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Backend) XXX_GraphQLType() string {
	return "Backend"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Backend) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Backend) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Backend) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Backend) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Backend{query: selectNode(dag.query, id, "Backend")}
	return nil
}

// Get a Service to run the backend
func (r *Backend) Serve() *Service { // backend (../../../../../.dagger/modules/backend/main.go:35:1)
	q := r.query.Select("serve")

	return &Service{
		query: q,
	}
}

// AsNode returns this Backend as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Backend) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

func (r *Query) Backend(binary *File) *Backend { // backend (../../../../../.dagger/modules/backend/main.go:12:1)
	assertNotNil("binary", binary)
	q := r.query.Select("backend")
	q = q.Arg("binary", binary)

	return &Backend{
		query: q,
	}
}
