// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Frontend struct { // frontend (../../../../../.dagger/modules/frontend/src/index.ts:15:14)
	query *querybuilder.Selection

	id *FrontendID
}

func (r *Frontend) WithGraphQLQuery(q *querybuilder.Selection) *Frontend {
	return &Frontend{
		query: q,
	}
}

func (r *Frontend) Build() *Directory { // frontend (../../../../../.dagger/modules/frontend/src/index.ts:24:3)
	q := r.query.Select("build")

	return &Directory{
		query: q,
	}
}

// A unique identifier for this Frontend.
func (r *Frontend) ID(ctx context.Context) (FrontendID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response FrontendID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Frontend) XXX_GraphQLType() string {
	return "Frontend"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Frontend) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Frontend) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Frontend) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Frontend) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Frontend{query: selectNode(dag.query, id, "Frontend")}
	return nil
}

func (r *Frontend) Serve() *Service { // frontend (../../../../../.dagger/modules/frontend/src/index.ts:30:3)
	q := r.query.Select("serve")

	return &Service{
		query: q,
	}
}

func (r *Frontend) Source() *Directory { // frontend (../../../../../.dagger/modules/frontend/src/index.ts:17:3)
	q := r.query.Select("source")

	return &Directory{
		query: q,
	}
}

// AsNode returns this Frontend as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Frontend) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// FrontendOpts contains options for Query.Frontend
type FrontendOpts struct {
	Source *Directory // frontend (../../../../../.dagger/modules/frontend/src/index.ts:19:54)
}

// A generated module for Frontend functions
func (r *Query) Frontend(opts ...FrontendOpts) *Frontend { // frontend (../../../../../:0:0)
	q := r.query.Select("frontend")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	return &Frontend{
		query: q,
	}
}
