// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Greetings struct { // greetings (../../../../../:0:0)
	query *querybuilder.Selection

	id *ID
}

func (r *Greetings) WithGraphQLQuery(q *querybuilder.Selection) *Greetings {
	return &Greetings{
		query: q,
	}
}

// Build the backend and frontend for a specified environment
func (r *Greetings) Build() *Directory {
	q := r.query.Select("build")

	return &Directory{
		query: q,
	}
}

// A unique identifier for this Greetings.
func (r *Greetings) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Greetings) XXX_GraphQLType() string {
	return "Greetings"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Greetings) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Greetings) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Greetings) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Greetings) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Greetings{query: selectNode(dag.query, id, "Greetings")}
	return nil
}

// GreetingsOpts contains options for Query.Greetings
type GreetingsOpts struct {
	Source *Directory
}

func (r *Query) Greetings(opts ...GreetingsOpts) *Greetings { // greetings (../../../../../:0:0)
	q := r.query.Select("greetings")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	return &Greetings{
		query: q,
	}
}
