/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */

import { Context, BaseClient } from "@dagger.io/dagger"
import {
  Directory,
  Service
} from "./dagger.gen.js"
import type {
  DirectoryID,
  FrontendID,
  ID,
  ServiceID
} from "./dagger.gen.js"


export type ClientFrontendOpts = {
  source?: Directory // frontend (.dagger/frontend/src/index.ts:19:54)
}


export class Frontend extends BaseClient { // frontend (.dagger/frontend/src/index.ts:15:14)
  private readonly _id?: FrontendID = undefined
  private readonly _checkDirectory?: string = undefined

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
     _id?: FrontendID,
     _checkDirectory?: string,
   ) {
     super(ctx)

     this._id = _id
     this._checkDirectory = _checkDirectory
   }

  /**
   * A unique identifier for this Frontend.
   */
  id = async (): Promise<FrontendID> => {
    if (this._id) {
      return this._id
    }

    const ctx = this._ctx.select(
      "id",
    )

    const response: Awaited<FrontendID> = await ctx.execute()

    
    return response
  }
  build = (): Directory => { // frontend (.dagger/frontend/src/index.ts:37:3)

    const ctx = this._ctx.select(
      "build",
    )
    return new Directory(ctx)
  }
  checkDirectory = async (source: Directory): Promise<string> => { // frontend (.dagger/frontend/src/index.ts:59:9)
    if (this._checkDirectory) {
      return this._checkDirectory
    }

    const ctx = this._ctx.select(
      "checkDirectory",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
  format = (): Directory => { // frontend (.dagger/frontend/src/index.ts:24:3)

    const ctx = this._ctx.select(
      "format",
    )
    return new Directory(ctx)
  }
  formatDirectory = (source: Directory): Directory => { // frontend (.dagger/frontend/src/index.ts:73:3)

    const ctx = this._ctx.select(
      "formatDirectory",
      { source },
    )
    return new Directory(ctx)
  }
  formatFile = (source: Directory, path: string): Directory => { // frontend (.dagger/frontend/src/index.ts:79:3)

    const ctx = this._ctx.select(
      "formatFile",
      { source, path },
    )
    return new Directory(ctx)
  }
  serve = (): Service => { // frontend (.dagger/frontend/src/index.ts:43:3)

    const ctx = this._ctx.select(
      "serve",
    )
    return new Service(ctx)
  }
  source = (): Directory => { // frontend (.dagger/frontend/src/index.ts:17:3)

    const ctx = this._ctx.select(
      "source",
    )
    return new Directory(ctx)
  }
}


declare module "./dagger.gen.js" {
  interface Client {
    frontend(opts?: ClientFrontendOpts): Frontend
  }
}

import type {
  Client as __Client
} from "./dagger.gen.js"

export function __applyFrontendAugmentations(scope: {
  Client: typeof __Client
}) {
  const { Client } = scope
  type Client = __Client

Client.prototype.frontend = function (this: any, opts?: ClientFrontendOpts): Frontend {

    const ctx = this._ctx.select(
      "frontend",
      { ...opts },
    )
    return new Frontend(ctx)
}
}