// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"backend/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Backend) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *Backend) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Backend":
		switch fnName {
		case "Binary":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var arch string
			if inputArgs["arch"] != nil {
				err = json.Unmarshal([]byte(inputArgs["arch"]), &arch)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg arch", err))
				}
			}
			return (*Backend).Binary(&parent, arch), nil
		case "Build":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var arch string
			if inputArgs["arch"] != nil {
				err = json.Unmarshal([]byte(inputArgs["arch"]), &arch)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg arch", err))
				}
			}
			return (*Backend).Build(&parent, arch), nil
		case "CheckDirectory":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Backend).CheckDirectory(&parent, ctx, source)
		case "Container":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var arch string
			if inputArgs["arch"] != nil {
				err = json.Unmarshal([]byte(inputArgs["arch"]), &arch)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg arch", err))
				}
			}
			return (*Backend).Container(&parent, arch), nil
		case "Format":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Backend).Format(&parent), nil
		case "FormatDirectory":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Backend).FormatDirectory(&parent, source), nil
		case "FormatFile":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var path string
			if inputArgs["path"] != nil {
				err = json.Unmarshal([]byte(inputArgs["path"]), &path)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg path", err))
				}
			}
			return (*Backend).FormatFile(&parent, source, path), nil
		case "Serve":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Backend).Serve(&parent), nil
		case "":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return New(source), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithObject(
				dag.TypeDef().WithObject("Backend", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 11, 6)}).
					WithFunction(
						dag.Function("Binary",
							dag.TypeDef().WithObject("File")).
							WithDescription("Return the compiled backend binary for a particular architecture").
							WithSourceMap(dag.SourceMap("main.go", 73, 1)).
							WithArg("arch", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 75, 2)})).
					WithFunction(
						dag.Function("Build",
							dag.TypeDef().WithObject("Directory")).
							WithDescription("Build the backend").
							WithSourceMap(dag.SourceMap("main.go", 58, 1)).
							WithArg("arch", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 60, 2)})).
					WithFunction(
						dag.Function("CheckDirectory",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Stateless checker").
							WithSourceMap(dag.SourceMap("main.go", 106, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{Description: "Directory to run checks on", SourceMap: dag.SourceMap("main.go", 109, 2)})).
					WithFunction(
						dag.Function("Container",
							dag.TypeDef().WithObject("Container")).
							WithDescription("Get a container ready to run the backend").
							WithSourceMap(dag.SourceMap("main.go", 82, 1)).
							WithArg("arch", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 84, 2)})).
					WithFunction(
						dag.Function("Format",
							dag.TypeDef().WithObject("Directory")).
							WithDescription("Formatter").
							WithSourceMap(dag.SourceMap("main.go", 50, 1))).
					WithFunction(
						dag.Function("FormatDirectory",
							dag.TypeDef().WithObject("Directory")).
							WithDescription("Stateless formatter").
							WithSourceMap(dag.SourceMap("main.go", 127, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{Description: "Directory to format", SourceMap: dag.SourceMap("main.go", 129, 2)})).
					WithFunction(
						dag.Function("FormatFile",
							dag.TypeDef().WithObject("Directory")).
							WithDescription("Stateless formatter").
							WithSourceMap(dag.SourceMap("main.go", 136, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{Description: "Directory with go module", SourceMap: dag.SourceMap("main.go", 138, 2)}).
							WithArg("path", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "File path to format", SourceMap: dag.SourceMap("main.go", 140, 2)})).
					WithFunction(
						dag.Function("Serve",
							dag.TypeDef().WithObject("Service")).
							WithDescription("Get a Service to run the backend").
							WithSourceMap(dag.SourceMap("main.go", 101, 1)).
							WithUp()).
					WithField("Source", dag.TypeDef().WithObject("Directory"), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("main.go", 12, 2)}).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("Backend")).
							WithSourceMap(dag.SourceMap("main.go", 15, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 19, 2), DefaultPath: "/", Ignore: []string{".git", "**/node_modules", "website"}}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
