// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// A Dagger module for Go - a programming language for building simple, secure, scalable systems.
//
// https://dagger.io
// https://golang.org
type Go struct { // go (../../../../:0:0)
	query *querybuilder.Selection

	id      *GoID
	lintAll *Void
	testAll *Void
	version *string
}

func (r *Go) WithGraphQLQuery(q *querybuilder.Selection) *Go {
	return &Go{
		query: q,
	}
}

// Base image used for Go test, generate, and helper containers.
func (r *Go) Base() *Container { // go (../../../../:0:0)
	q := r.query.Select("base")

	return &Container{
		query: q,
	}
}

// Module roots to run go generate in ("!" excludes; see `lint`).
func (r *Go) Generate(ctx context.Context) ([]string, error) { // go (../../../../:0:0)
	q := r.query.Select("generate")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Run go generate in every discovered Go module.
// Modules configured to skip generate, or without go:generate directives,
// are skipped.
func (r *Go) GenerateAll(ws *Workspace) *Changeset { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("generateAll")
	q = q.Arg("ws", ws)

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this Go.
func (r *Go) ID(ctx context.Context) (GoID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response GoID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Go) XXX_GraphQLType() string {
	return "Go"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Go) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Go) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Go) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Go) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Go{query: selectNode(dag.query, id, "Go")}
	return nil
}

// Extra workspace-root include patterns mounted for each module's Go commands.
// Use this for fixtures, generator inputs, or other files not covered by the
// built-in Go patterns.
func (r *Go) IncludeExtraFiles(ctx context.Context) ([]string, error) { // go (../../../../:0:0)
	q := r.query.Select("includeExtraFiles")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Module roots to lint ("!" excludes; see the `lint` constructor argument).
func (r *Go) Lint(ctx context.Context) ([]string, error) { // go (../../../../:0:0)
	q := r.query.Select("lint")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Run golangci-lint in every discovered Go module.
// Modules configured to skip lint are skipped.
func (r *Go) LintAll(ctx context.Context, ws *Workspace) error { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	if r.lintAll != nil {
		return nil
	}
	q := r.query.Select("lintAll")
	q = q.Arg("ws", ws)

	return q.Execute(ctx)
}

// GoModuleOpts contains options for Go.Module
type GoModuleOpts struct {
	FindUp bool // go (../../../../:0:0)
}

// Return the Go module containing a workspace path.
//
// By default, path may be a module root or a directory inside a module. Set
// findUp to false when path is already a module root and no lookup is needed.
func (r *Go) Module(ws *Workspace, path string, opts ...GoModuleOpts) *GoModule { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("module")
	for i := len(opts) - 1; i >= 0; i-- {
		// `findUp` optional argument
		if !querybuilder.IsZeroValue(opts[i].FindUp) {
			q = q.Arg("findUp", opts[i].FindUp)
		}
	}
	q = q.Arg("ws", ws)
	q = q.Arg("path", path)

	return &GoModule{
		query: q,
	}
}

// GoModulesOpts contains options for Go.Modules
type GoModulesOpts struct {
	Include []string // go (../../../../:0:0)

	Exclude []string // go (../../../../:0:0)

	IncludeSkipLint bool // go (../../../../:0:0)

	IncludeSkipTest bool // go (../../../../:0:0)

	IncludeSkipGenerate bool // go (../../../../:0:0)
}

// Go modules discovered from go.mod files at or below the working directory,
// plus the enclosing module when the cwd is inside one. Optional include/exclude
// patterns filter the discovered module roots.
func (r *Go) Modules(ctx context.Context, ws *Workspace, opts ...GoModulesOpts) ([]GoModule, error) { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("modules")
	for i := len(opts) - 1; i >= 0; i-- {
		// `include` optional argument
		if !querybuilder.IsZeroValue(opts[i].Include) {
			q = q.Arg("include", opts[i].Include)
		}
		// `exclude` optional argument
		if !querybuilder.IsZeroValue(opts[i].Exclude) {
			q = q.Arg("exclude", opts[i].Exclude)
		}
		// `includeSkipLint` optional argument
		if !querybuilder.IsZeroValue(opts[i].IncludeSkipLint) {
			q = q.Arg("includeSkipLint", opts[i].IncludeSkipLint)
		}
		// `includeSkipTest` optional argument
		if !querybuilder.IsZeroValue(opts[i].IncludeSkipTest) {
			q = q.Arg("includeSkipTest", opts[i].IncludeSkipTest)
		}
		// `includeSkipGenerate` optional argument
		if !querybuilder.IsZeroValue(opts[i].IncludeSkipGenerate) {
			q = q.Arg("includeSkipGenerate", opts[i].IncludeSkipGenerate)
		}
	}
	q = q.Arg("ws", ws)

	q = q.Select("id")

	type modules struct {
		Id GoModuleID
	}

	convert := func(fields []modules) []GoModule {
		out := []GoModule{}

		for i := range fields {
			val := GoModule{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "GoModule")
			out = append(out, val)
		}

		return out
	}
	var response []modules

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// Module roots to test ("!" excludes; see the `lint` constructor argument).
func (r *Go) Test(ctx context.Context) ([]string, error) { // go (../../../../:0:0)
	q := r.query.Select("test")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Run tests in every discovered Go module.
// Modules configured to skip tests are skipped.
func (r *Go) TestAll(ctx context.Context, ws *Workspace) error { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	if r.testAll != nil {
		return nil
	}
	q := r.query.Select("testAll")
	q = q.Arg("ws", ws)

	return q.Execute(ctx)
}

// Go version used for the default Go base image. Null when a custom base is set.
func (r *Go) Version(ctx context.Context) (string, error) { // go (../../../../:0:0)
	if r.version != nil {
		return *r.version, nil
	}
	q := r.query.Select("version")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this Go as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Go) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// A workspace directory containing Go test files.
type GoDirectory struct { // go (../../../../:0:0)
	query *querybuilder.Selection

	execute *Void
	id      *GoDirectoryID
	path    *string
}

func (r *GoDirectory) WithGraphQLQuery(q *querybuilder.Selection) *GoDirectory {
	return &GoDirectory{
		query: q,
	}
}

// Run Go tests in this directory.
func (r *GoDirectory) Execute(ctx context.Context) error { // go (../../../../:0:0)
	if r.execute != nil {
		return nil
	}
	q := r.query.Select("execute")

	return q.Execute(ctx)
}

// A unique identifier for this GoDirectory.
func (r *GoDirectory) ID(ctx context.Context) (GoDirectoryID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response GoDirectoryID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *GoDirectory) XXX_GraphQLType() string {
	return "GoDirectory"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *GoDirectory) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *GoDirectory) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *GoDirectory) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *GoDirectory) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = GoDirectory{query: selectNode(dag.query, id, "GoDirectory")}
	return nil
}

// Workspace-relative path of this directory.
func (r *GoDirectory) Path(ctx context.Context) (string, error) { // go (../../../../:0:0)
	if r.path != nil {
		return *r.path, nil
	}
	q := r.query.Select("path")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this GoDirectory as a Node.
// This is a local type conversion — no GraphQL call.
func (r *GoDirectory) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// A Go module rooted at a workspace-relative path.
type GoModule struct { // go (../../../../:0:0)
	query *querybuilder.Selection

	hasGenerateDirectives *bool
	id                    *GoModuleID
	lint                  *Void
	path                  *string
	skipGenerate          *bool
	skipLint              *bool
	skipTest              *bool
	test                  *Void
	version               *string
}

func (r *GoModule) WithGraphQLQuery(q *querybuilder.Selection) *GoModule {
	return &GoModule{
		query: q,
	}
}

// Base Go container before source files and commands are added.
func (r *GoModule) Base() *Container { // go (../../../../:0:0)
	q := r.query.Select("base")

	return &Container{
		query: q,
	}
}

// Changes made by running go generate in this module.
// If this module is configured to skip generate or no go:generate directives are
// found, the changeset is empty.
func (r *GoModule) Generate(ws *Workspace) *Changeset { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("generate")
	q = q.Arg("ws", ws)

	return &Changeset{
		query: q,
	}
}

// Whether this module's Go files contain a go:generate directive.
func (r *GoModule) HasGenerateDirectives(ctx context.Context, ws *Workspace) (bool, error) { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	if r.hasGenerateDirectives != nil {
		return *r.hasGenerateDirectives, nil
	}
	q := r.query.Select("hasGenerateDirectives")
	q = q.Arg("ws", ws)

	var response bool

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this GoModule.
func (r *GoModule) ID(ctx context.Context) (GoModuleID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response GoModuleID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *GoModule) XXX_GraphQLType() string {
	return "GoModule"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *GoModule) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *GoModule) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *GoModule) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *GoModule) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = GoModule{query: selectNode(dag.query, id, "GoModule")}
	return nil
}

// GoModuleIncludeOpts contains options for GoModule.Include
type GoModuleIncludeOpts struct {
	Lint bool // go (../../../../:0:0)

	Test bool // go (../../../../:0:0)

	Generate bool // go (../../../../:0:0)
}

// Final workspace include patterns used to build this module's source directory.
// With no include flags, defaults to test inputs.
func (r *GoModule) Include(ctx context.Context, ws *Workspace, opts ...GoModuleIncludeOpts) ([]string, error) { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("include")
	for i := len(opts) - 1; i >= 0; i-- {
		// `lint` optional argument
		if !querybuilder.IsZeroValue(opts[i].Lint) {
			q = q.Arg("lint", opts[i].Lint)
		}
		// `test` optional argument
		if !querybuilder.IsZeroValue(opts[i].Test) {
			q = q.Arg("test", opts[i].Test)
		}
		// `generate` optional argument
		if !querybuilder.IsZeroValue(opts[i].Generate) {
			q = q.Arg("generate", opts[i].Generate)
		}
	}
	q = q.Arg("ws", ws)

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Built-in workspace include patterns for this module's own Go source files.
func (r *GoModule) IncludeBase(ctx context.Context) ([]string, error) { // go (../../../../:0:0)
	q := r.query.Select("includeBase")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GoModuleIncludeDiscoveredOpts contains options for GoModule.IncludeDiscovered
type GoModuleIncludeDiscoveredOpts struct {
	Lint bool // go (../../../../:0:0)

	Test bool // go (../../../../:0:0)

	Generate bool // go (../../../../:0:0)
}

// Additional workspace include patterns discovered by scanning Go directives
// and local go.mod replaces reachable from this module's include graph.
// With no include flags, defaults to test inputs.
func (r *GoModule) IncludeDiscovered(ctx context.Context, ws *Workspace, opts ...GoModuleIncludeDiscoveredOpts) ([]string, error) { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("includeDiscovered")
	for i := len(opts) - 1; i >= 0; i-- {
		// `lint` optional argument
		if !querybuilder.IsZeroValue(opts[i].Lint) {
			q = q.Arg("lint", opts[i].Lint)
		}
		// `test` optional argument
		if !querybuilder.IsZeroValue(opts[i].Test) {
			q = q.Arg("test", opts[i].Test)
		}
		// `generate` optional argument
		if !querybuilder.IsZeroValue(opts[i].Generate) {
			q = q.Arg("generate", opts[i].Generate)
		}
	}
	q = q.Arg("ws", ws)

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Extra workspace-root include patterns mounted for this module's Go commands.
func (r *GoModule) IncludeExtraFiles(ctx context.Context) ([]string, error) { // go (../../../../:0:0)
	q := r.query.Select("includeExtraFiles")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Run golangci-lint in this module.
// If this module is configured to skip lint, no lint check is run.
func (r *GoModule) Lint(ctx context.Context, ws *Workspace) error { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	if r.lint != nil {
		return nil
	}
	q := r.query.Select("lint")
	q = q.Arg("ws", ws)

	return q.Execute(ctx)
}

// Workspace-relative path of this module root.
func (r *GoModule) Path(ctx context.Context) (string, error) { // go (../../../../:0:0)
	if r.path != nil {
		return *r.path, nil
	}
	q := r.query.Select("path")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Whether this module falls outside the configured go generate selection.
func (r *GoModule) SkipGenerate(ctx context.Context, ws *Workspace) (bool, error) { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	if r.skipGenerate != nil {
		return *r.skipGenerate, nil
	}
	q := r.query.Select("skipGenerate")
	q = q.Arg("ws", ws)

	var response bool

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Whether this module falls outside the configured lint selection.
func (r *GoModule) SkipLint(ctx context.Context, ws *Workspace) (bool, error) { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	if r.skipLint != nil {
		return *r.skipLint, nil
	}
	q := r.query.Select("skipLint")
	q = q.Arg("ws", ws)

	var response bool

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Whether this module falls outside the configured test selection.
func (r *GoModule) SkipTest(ctx context.Context, ws *Workspace) (bool, error) { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	if r.skipTest != nil {
		return *r.skipTest, nil
	}
	q := r.query.Select("skipTest")
	q = q.Arg("ws", ws)

	var response bool

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GoModuleSourceOpts contains options for GoModule.Source
type GoModuleSourceOpts struct {
	Lint bool // go (../../../../:0:0)

	Test bool // go (../../../../:0:0)

	Generate bool // go (../../../../:0:0)
}

// Workspace source mounted for this module's Go commands.
// With no include flags, defaults to test inputs.
func (r *GoModule) Source(ws *Workspace, opts ...GoModuleSourceOpts) *Directory { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("source")
	for i := len(opts) - 1; i >= 0; i-- {
		// `lint` optional argument
		if !querybuilder.IsZeroValue(opts[i].Lint) {
			q = q.Arg("lint", opts[i].Lint)
		}
		// `test` optional argument
		if !querybuilder.IsZeroValue(opts[i].Test) {
			q = q.Arg("test", opts[i].Test)
		}
		// `generate` optional argument
		if !querybuilder.IsZeroValue(opts[i].Generate) {
			q = q.Arg("generate", opts[i].Generate)
		}
	}
	q = q.Arg("ws", ws)

	return &Directory{
		query: q,
	}
}

// Run tests in this module.
// If this module is configured to skip tests, no tests are run.
func (r *GoModule) Test(ctx context.Context, ws *Workspace) error { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	if r.test != nil {
		return nil
	}
	q := r.query.Select("test")
	q = q.Arg("ws", ws)

	return q.Execute(ctx)
}

// Workspace testdata directories mounted while testing this module.
func (r *GoModule) TestData(ws *Workspace) *Directory { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("testData")
	q = q.Arg("ws", ws)

	return &Directory{
		query: q,
	}
}

// Directories in this module containing Go test files.
func (r *GoModule) TestDirectories(ctx context.Context, ws *Workspace) ([]GoDirectory, error) { // go (../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("testDirectories")
	q = q.Arg("ws", ws)

	q = q.Select("id")

	type testDirectories struct {
		Id GoDirectoryID
	}

	convert := func(fields []testDirectories) []GoDirectory {
		out := []GoDirectory{}

		for i := range fields {
			val := GoDirectory{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "GoDirectory")
			out = append(out, val)
		}

		return out
	}
	var response []testDirectories

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// Go version configured on the root Go module. Null when a custom base is set.
func (r *GoModule) Version(ctx context.Context) (string, error) { // go (../../../../:0:0)
	if r.version != nil {
		return *r.version, nil
	}
	q := r.query.Select("version")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this GoModule as a Node.
// This is a local type conversion — no GraphQL call.
func (r *GoModule) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// GoOpts contains options for Query.Go
type GoOpts struct {
	//
	// Go version used for the default Go base image.
	//
	Version string // go (../../../../:0:0)
	//
	// Base image used for Go test, generate, and helper containers.
	// Mutually exclusive with version.
	//
	Base *Container // go (../../../../:0:0)
	//
	// Extra workspace-root include patterns mounted for each module's Go commands.
	// Use this for fixtures, generator inputs, or other files not covered by the
	// built-in Go patterns.
	//
	IncludeExtraFiles []string // go (../../../../:0:0)
	//
	// Module roots to lint. A bare pattern selects, a "!"-prefixed pattern
	// excludes, and an exclude always wins (order does not matter). With no
	// selecting pattern, every module is linted. Supported patterns: "**" or "*"
	// (all modules), and "X" or "X/**" (module X and any module below it); other
	// glob forms (mid-path "**", single-segment "*") are not interpreted. For
	// example ["**", "!docs"] lints all but docs; ["e2e/**"] lints only e2e;
	// ["!**"] lints nothing.
	//
	Lint []string // go (../../../../:0:0)
	//
	// Module roots to test. Same selection rules as `lint`.
	//
	Test []string // go (../../../../:0:0)
	//
	// Module roots to run go generate in. Same selection rules as `lint`.
	//
	Generate []string // go (../../../../:0:0)
}

// A Dagger module for Go - a programming language for building simple, secure, scalable systems.
//
// https://dagger.io
// https://golang.org
func (r *Query) Go(opts ...GoOpts) *Go { // go (../../../../:0:0)
	q := r.query.Select("go")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `base` optional argument
		if !querybuilder.IsZeroValue(opts[i].Base) {
			q = q.Arg("base", opts[i].Base)
		}
		// `includeExtraFiles` optional argument
		if !querybuilder.IsZeroValue(opts[i].IncludeExtraFiles) {
			q = q.Arg("includeExtraFiles", opts[i].IncludeExtraFiles)
		}
		// `lint` optional argument
		if !querybuilder.IsZeroValue(opts[i].Lint) {
			q = q.Arg("lint", opts[i].Lint)
		}
		// `test` optional argument
		if !querybuilder.IsZeroValue(opts[i].Test) {
			q = q.Arg("test", opts[i].Test)
		}
		// `generate` optional argument
		if !querybuilder.IsZeroValue(opts[i].Generate) {
			q = q.Arg("generate", opts[i].Generate)
		}
	}

	return &Go{
		query: q,
	}
}
