// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Golang
func (r *Binding) AsGolang() *Golang { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L21)
	q := r.query.Select("asGolang")

	return &Golang{
		query: q,
	}
}

// Create or update a binding of type Golang in the environment
func (r *Env) WithGolangInput(name string, value *Golang, description string) *Env { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L21)
	assertNotNil("value", value)
	q := r.query.Select("withGolangInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Golang output to be assigned in the environment
func (r *Env) WithGolangOutput(name string, description string) *Env { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L21)
	q := r.query.Select("withGolangOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Golang struct { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L21)
	query *querybuilder.Selection

	golangciLint *string
	id           *GolangID
	test         *string
}
type WithGolangFunc func(r *Golang) *Golang

// With calls the provided function with current Golang.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *Golang) With(f WithGolangFunc) *Golang {
	return f(r)
}

func (r *Golang) WithGraphQLQuery(q *querybuilder.Selection) *Golang {
	return &Golang{
		query: q,
	}
}

// GolangBaseOpts contains options for Golang.Base
type GolangBaseOpts struct {
	//
	// Golang image tag to use
	//
	//
	// Default: "1.24"
	Version string // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L192)
}

// Sets up the Container with a golang image and cache volumes
func (r *Golang) Base(opts ...GolangBaseOpts) *Golang { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L189)
	q := r.query.Select("base")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return &Golang{
		query: q,
	}
}

// GolangBuildOpts contains options for Golang.Build
type GolangBuildOpts struct {
	//
	// The Go source code to build
	//
	Source *Directory // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L54)
	//
	// The architecture for GOARCH
	//
	Arch string // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L59)
	//
	// The operating system for GOOS
	//
	Os string // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L62)
}

// Build the Go project
func (r *Golang) Build(args []string, opts ...GolangBuildOpts) *Directory { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L51)
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
		// `os` optional argument
		if !querybuilder.IsZeroValue(opts[i].Os) {
			q = q.Arg("os", opts[i].Os)
		}
	}
	q = q.Arg("args", args)

	return &Directory{
		query: q,
	}
}

// GolangBuildContainerOpts contains options for Golang.BuildContainer
type GolangBuildContainerOpts struct {
	//
	// The Go source code to build
	//
	Source *Directory // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L87)
	//
	// Arguments to `go build`
	//
	Args []string // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L90)
	//
	// The architecture for GOARCH
	//
	Arch string // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L93)
	//
	// The operating system for GOOS
	//
	Os string // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L96)
	//
	// Base container in which to copy the build
	//
	Base *Container // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L99)
}

// Build a Go project returning a Container containing the build
func (r *Golang) BuildContainer(opts ...GolangBuildContainerOpts) *Container { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L84)
	q := r.query.Select("buildContainer")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `args` optional argument
		if !querybuilder.IsZeroValue(opts[i].Args) {
			q = q.Arg("args", opts[i].Args)
		}
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
		// `os` optional argument
		if !querybuilder.IsZeroValue(opts[i].Os) {
			q = q.Arg("os", opts[i].Os)
		}
		// `base` optional argument
		if !querybuilder.IsZeroValue(opts[i].Base) {
			q = q.Arg("base", opts[i].Base)
		}
	}

	return &Container{
		query: q,
	}
}

// Golang container with the go project and go toolchain
func (r *Golang) Container() *Container { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L23)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// GolangFmtOpts contains options for Golang.Fmt
type GolangFmtOpts struct {
	//
	// The Go source code to format
	//
	Source *Directory // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L132)
	//
	// Arguments to `go fmt`
	// +default "./..."
	//
	Args []string // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L136)
}

// Format the Go project
func (r *Golang) Fmt(opts ...GolangFmtOpts) *Golang { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L128)
	q := r.query.Select("fmt")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `args` optional argument
		if !querybuilder.IsZeroValue(opts[i].Args) {
			q = q.Arg("args", opts[i].Args)
		}
	}

	return &Golang{
		query: q,
	}
}

// Get the current state of the source directory
func (r *Golang) GetSource() *Directory { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L210)
	q := r.query.Select("getSource")

	return &Directory{
		query: q,
	}
}

// GolangGolangciLintOpts contains options for Golang.GolangciLint
type GolangGolangciLintOpts struct {
	//
	// The Go source code to lint
	//
	Source *Directory // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L155)
}

// Lint the Go project
func (r *Golang) GolangciLint(ctx context.Context, opts ...GolangGolangciLintOpts) (string, error) { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L151)
	if r.golangciLint != nil {
		return *r.golangciLint, nil
	}
	q := r.query.Select("golangciLint")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GolangGolangciLintFixOpts contains options for Golang.GolangciLintFix
type GolangGolangciLintFixOpts struct {
	//
	// The Go source code to lint
	//
	Source *Directory // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L166)
}

// Lint the Go project and apply fixes
func (r *Golang) GolangciLintFix(opts ...GolangGolangciLintFixOpts) *Directory { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L162)
	q := r.query.Select("golangciLintFix")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	return &Directory{
		query: q,
	}
}

// A unique identifier for this Golang.
func (r *Golang) ID(ctx context.Context) (GolangID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response GolangID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Golang) XXX_GraphQLType() string {
	return "Golang"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Golang) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Golang) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Golang) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Golang) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Golang{query: selectNode(dag.query, id, "Golang")}
	return nil
}

// GolangTestOpts contains options for Golang.Test
type GolangTestOpts struct {
	//
	// The Go source code to test
	//
	Source *Directory // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L114)
	//
	// Arguments to `go test`
	// +default "./..."
	//
	Args []string // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L118)
}

// Test the Go project
func (r *Golang) Test(ctx context.Context, opts ...GolangTestOpts) (string, error) { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L110)
	if r.test != nil {
		return *r.test, nil
	}
	q := r.query.Select("test")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `args` optional argument
		if !querybuilder.IsZeroValue(opts[i].Args) {
			q = q.Arg("args", opts[i].Args)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Bring your own container
func (r *Golang) WithContainer(ctr *Container) *Golang { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L215)
	assertNotNil("ctr", ctr)
	q := r.query.Select("withContainer")
	q = q.Arg("ctr", ctr)

	return &Golang{
		query: q,
	}
}

// Specify the Source to use in the module
func (r *Golang) WithSource(source *Directory) *Golang { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L204)
	assertNotNil("source", source)
	q := r.query.Select("withSource")
	q = q.Arg("source", source)

	return &Golang{
		query: q,
	}
}

// AsNode returns this Golang as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Golang) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// GolangOpts contains options for Query.Golang
type GolangOpts struct {
	//
	// Specify an alternative container to index.docker.io/golang
	//
	Ctr *Container // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L29)
	//
	// The source directory of the Go project
	//
	Source *Directory // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L32)
	//
	// Golang image tag to use
	//
	//
	// Default: "1.24"
	Version string // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L35)
}

// Build Go projects
//
// A utility module for building, testing, and linting Go projects
func (r *Query) Golang(opts ...GolangOpts) *Golang { // golang (https://github.com/kpenfound/dagger-modules/tree/f7964245d0146dd3810f247c6c09eb33518d4654/golang/main.go#L26)
	q := r.query.Select("golang")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ctr` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ctr) {
			q = q.Arg("ctr", opts[i].Ctr)
		}
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return &Golang{
		query: q,
	}
}
