// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// A unique identifier for an object.
type CodeWorkspaceCheckableID = ID // code-workspace (../../../../:0:0)

// A unique identifier for an object.
type CodeWorkspaceID = ID // code-workspace (../../../../:0:0)

// Place to do work and check it
type CodeWorkspace struct { // code-workspace (../../../../:0:0)
	query *querybuilder.Selection

	check *string
	diff  *string
	id    *CodeWorkspaceID
	read  *string
	tree  *string
}
type WithCodeWorkspaceFunc func(r *CodeWorkspace) *CodeWorkspace

// With calls the provided function with current CodeWorkspace.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *CodeWorkspace) With(f WithCodeWorkspaceFunc) *CodeWorkspace {
	return f(r)
}

func (r *CodeWorkspace) WithGraphQLQuery(q *querybuilder.Selection) *CodeWorkspace {
	return &CodeWorkspace{
		query: q,
	}
}

// Run the tests in the workspace
func (r *CodeWorkspace) Check(ctx context.Context) (string, error) {
	if r.check != nil {
		return *r.check, nil
	}
	q := r.query.Select("check")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Show the changes made to the workspace so far in unified diff format
func (r *CodeWorkspace) Diff(ctx context.Context) (string, error) {
	if r.diff != nil {
		return *r.diff, nil
	}
	q := r.query.Select("diff")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this CodeWorkspace.
func (r *CodeWorkspace) ID(ctx context.Context) (CodeWorkspaceID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response CodeWorkspaceID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *CodeWorkspace) XXX_GraphQLType() string {
	return "CodeWorkspace"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *CodeWorkspace) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *CodeWorkspace) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *CodeWorkspace) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *CodeWorkspace) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = CodeWorkspace{query: selectNode(dag.query, id, "CodeWorkspace")}
	return nil
}

// Read the contents of a file in the workspace at the given path
func (r *CodeWorkspace) Read(ctx context.Context, path string) (string, error) {
	if r.read != nil {
		return *r.read, nil
	}
	q := r.query.Select("read")
	q = q.Arg("path", path)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Reset the workspace to the original state
func (r *CodeWorkspace) Reset() *CodeWorkspace {
	q := r.query.Select("reset")

	return &CodeWorkspace{
		query: q,
	}
}

// List the files in the workspace in tree format
func (r *CodeWorkspace) Tree(ctx context.Context) (string, error) {
	if r.tree != nil {
		return *r.tree, nil
	}
	q := r.query.Select("tree")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *CodeWorkspace) Work() *Directory {
	q := r.query.Select("work")

	return &Directory{
		query: q,
	}
}

// Write the contents of a file in the workspace at the given path
func (r *CodeWorkspace) Write(path string, contents string) *CodeWorkspace {
	q := r.query.Select("write")
	q = q.Arg("path", path)
	q = q.Arg("contents", contents)

	return &CodeWorkspace{
		query: q,
	}
}

func (r *Query) CodeWorkspace(source *Directory, checker *CodeWorkspaceCheckable) *CodeWorkspace { // code-workspace (../../../../:0:0)
	assertNotNil("source", source)
	assertNotNil("checker", checker)
	q := r.query.Select("codeWorkspace")
	q = q.Arg("source", source)
	q = q.Arg("checker", checker)

	return &CodeWorkspace{
		query: q,
	}
}

// Interface for something that can be checked
type CodeWorkspaceCheckable struct { // code-workspace (../../../../:0:0)
	query *querybuilder.Selection

	checkDirectory *string
	id             *CodeWorkspaceCheckableID
}

type CodeWorkspaceCheckableClient = CodeWorkspaceCheckable

func (r *CodeWorkspaceCheckable) WithGraphQLQuery(q *querybuilder.Selection) *CodeWorkspaceCheckable {
	return &CodeWorkspaceCheckable{
		query: q,
	}
}

func (r *CodeWorkspaceCheckable) CheckDirectory(ctx context.Context, source *Directory) (string, error) {
	assertNotNil("source", source)
	if r.checkDirectory != nil {
		return *r.checkDirectory, nil
	}
	q := r.query.Select("checkDirectory")
	q = q.Arg("source", source)

	var response string
	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *CodeWorkspaceCheckable) FormatFile(source *Directory, path string) *Directory {
	assertNotNil("source", source)
	q := r.query.Select("formatFile")
	q = q.Arg("source", source)
	q = q.Arg("path", path)

	return &Directory{
		query: q,
	}
}

// A unique identifier for this CodeWorkspaceCheckable.
func (r *CodeWorkspaceCheckable) ID(ctx context.Context) (CodeWorkspaceCheckableID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response CodeWorkspaceCheckableID
	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *CodeWorkspaceCheckable) XXX_GraphQLType() string {
	return "CodeWorkspaceCheckable"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *CodeWorkspaceCheckable) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *CodeWorkspaceCheckable) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *CodeWorkspaceCheckable) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *CodeWorkspaceCheckable) UnmarshalJSON(bs []byte) error {
	var id CodeWorkspaceCheckableID
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = CodeWorkspaceCheckable{query: selectNode(dag.query, id, "CodeWorkspaceCheckable")}
	return nil
}
