/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */

import { Context, BaseClient } from "./core.js"
import {
  Directory,
  Service
} from "./client.gen.js"
import type {
  DirectoryID,
  ID,
  ServiceID
} from "./client.gen.js"


export type FrontendID = string & { __FrontendID: never }

export type ClientFrontendOpts = {
  source?: Directory // frontend (../.dagger/modules/frontend/src/index.ts:19:54)
}


export class Frontend extends BaseClient { // frontend (../.dagger/modules/frontend/src/index.ts:15:14)
  private readonly _id?: FrontendID = undefined

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
     _id?: FrontendID,
   ) {
     super(ctx)

     this._id = _id
   }

  /**
   * A unique identifier for this Frontend.
   */
  id = async (): Promise<FrontendID> => {
    if (this._id) {
      return this._id
    }

    const ctx = this._ctx.select(
      "id",
    )

    const response: Awaited<FrontendID> = await ctx.execute()

    
    return response
  }
  build = (): Directory => { // frontend (../.dagger/modules/frontend/src/index.ts:24:3)

    const ctx = this._ctx.select(
      "build",
    )
    return new Directory(ctx)
  }
  serve = (): Service => { // frontend (../.dagger/modules/frontend/src/index.ts:30:3)

    const ctx = this._ctx.select(
      "serve",
    )
    return new Service(ctx)
  }
  source = (): Directory => { // frontend (../.dagger/modules/frontend/src/index.ts:17:3)

    const ctx = this._ctx.select(
      "source",
    )
    return new Directory(ctx)
  }
}


declare module "./client.gen.js" {
  interface Client {
    frontend(opts?: ClientFrontendOpts): Frontend
  }
}

import type {
  Client as __Client
} from "./client.gen.js"

export function __applyFrontendAugmentations(scope: {
  Client: typeof __Client
}) {
  const { Client } = scope
  type Client = __Client

Client.prototype.frontend = function (this: any, opts?: ClientFrontendOpts): Frontend {

    const ctx = this._ctx.select(
      "frontend",
      { ...opts },
    )
    return new Frontend(ctx)
}
}