name: Checks
# Trigger the workflow on pushes to the main branch
on:
  push:
    branches: ["**"]

jobs:
  run:
    # Use Ubuntu latest runner
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dagger checks
        uses: dagger/dagger-for-github@main
        with:
          dagger-flags: "--cloud"
          check: "**"
          cloud-token: ${{ secrets.DAGGER_CLOUD_COMPUTE_TOKEN }}
          version: "latest"
